import {randomUUID}from 'node:crypto';import {requireRule}from './authority.mjs';import {feet,finitePositive}from './units.mjs';import {transition}from './state.mjs';
export function distanceMetres(a,b){const r=Math.PI/180,dlat=(b.lat-a.lat)*r,dlng=(b.lng-a.lng)*r,x=Math.sin(dlat/2)**2+Math.cos(a.lat*r)*Math.cos(b.lat*r)*Math.sin(dlng/2)**2;return 6371000*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));}
export function measure(m,type,upturn=m.upturn){
 requireRule(['dimensions','direct'].includes(m.method),'MEASUREMENT_METHOD','Choose measurement method');const factor=m.unit==='M'?1/.3048:1;requireRule(['FT','M'].includes(m.unit),'UNIT','Choose feet or metres');
 const floor=m.method==='dimensions'?feet(m.length,m.unit)*feet(m.width,m.unit):finitePositive(m.floorArea,'Floor area')*factor**2;
 const perimeter=m.method==='dimensions'?2*(feet(m.length,m.unit)+feet(m.width,m.unit)):finitePositive(m.perimeter,'Perimeter')*factor;
 requireRule(Number.isFinite(upturn)&&upturn>=0&&upturn<=10,'UPTURN','Upturn must be 0–10 feet');
 const showerLength=Number(m.showerLength||0)*factor,showerHeight=Number(m.showerHeight||0)*factor;requireRule(showerLength>=0&&showerHeight>=0&&showerHeight<=30&&showerLength<=perimeter,'SHOWER_DIMENSIONS','Check shower dimensions');
 for(const key of ['drains','penetrations'])requireRule(Number.isInteger(m[key])&&m[key]>=0&&m[key]<=100,'LINEAR_INPUT','Enter whole drain/penetration counts');
 const treated=floor+perimeter*upturn+(type==='BATHROOM'?showerLength*Math.max(0,showerHeight-upturn):0);requireRule(Number.isFinite(treated)&&treated<=100000,'AREA_RANGE','Treated area exceeds the supported 100,000 sq ft limit');
 const decimal=value=>Number(value.toFixed(12));return {floor:decimal(floor),perimeter:decimal(perimeter),upturn,showerExtra:decimal(type==='BATHROOM'?showerLength*Math.max(0,showerHeight-upturn):0),treated:decimal(treated),method:m.method,assumption:m.method==='direct'?'Explicit perimeter supplied':'Rectangular dimensions'};
}
export function diagnose(catalog,type,answers){for(const question of catalog.checklists[type]){if(question.optional&&answers[question.key]==null)continue;const value=answers[question.key];const valid=question.type==='bool'?typeof value==='boolean':question.type==='bool_yes_no'?['YES','NO'].includes(value):question.type==='number'?Number.isFinite(value):question.options.includes(value);requireRule(valid,'CHECKLIST_REQUIRED','Answer '+question.key.replaceAll('_',' '));}const structural=catalog.structural_flag_rules[type].filter(rule=>{const [key,value]=rule.split(':');return answers[key]===value});return {structural,blocking:structural.length?'Structural concern: technical clearance required':type==='BATHROOM'&&answers.tiles_removed==='NO'?'Tile removal required before warrantable quote':null};}
export const diagnosisHandlers={
 CHECK_IN:(s,p,a)=>{requireRule(s.job&&a==='applicator'&&s.job.applicatorId===s.profile.id,'NOT_ASSIGNED','Assigned applicator only');requireRule(s.profile.loggedIn,'LOGIN_REQUIRED','Sign in first');const l=p.location;requireRule(l&&Number.isFinite(l.lat)&&Number.isFinite(l.lng)&&Math.abs(l.lat)<=90&&Math.abs(l.lng)<=180&&Number.isFinite(l.accuracy)&&l.accuracy>0&&['live','sample'].includes(l.mode),'LOCATION_REQUIRED','Valid location and accuracy required');s.job.status=transition(s.job.status,'CHECK_IN',a);s.job.checkin={...l,distance:distanceMetres(s.job.site,l),at:s.clock.now};},
 SAVE_DIAGNOSIS:(s,p,a)=>{requireRule(a==='applicator'&&s.job?.status==='DIAGNOSIS','STATE_BLOCK','Check in before diagnosis');const analysis=diagnose(s.catalog,s.job.areaType,p.answers);const area=measure(p.measurement,s.job.areaType);requireRule(Array.isArray(p.photos)&&s.catalog.diagnosis_photos[s.job.areaType].every(view=>p.photos.some(photo=>photo.view===view)),'DIAGNOSIS_PHOTOS','Record all diagnosis views');requireRule(p.photos.every(photo=>['sample','camera'].includes(photo.mode)),'PHOTO_MODE','Label evidence mode');s.job.plan=null;s.job.structuralClearance=null;s.job.diagnosis={id:randomUUID(),version:(s.job.diagnosis?.version||0)+1,answers:p.answers,measurement:p.measurement,area,photos:p.photos,analysis,at:s.clock.now};},
 CLEAR_STRUCTURAL:(s,p,a)=>{requireRule(a==='admin'&&s.job?.diagnosis?.analysis.structural.length,'STRUCTURAL_REVIEW','Technical review required');requireRule(String(p.reason||'').trim().length>=15,'TECHNICAL_REASON','Enter a detailed technical clearance reason');s.job.structuralClearance={reviewer:'Demo technical supervisor',diagnosisId:s.job.diagnosis.id,reason:p.reason,at:s.clock.now};}
};


