import {settleBase}from './rewards.mjs';
import {createHash,randomUUID} from 'node:crypto';
import {requireRule,message} from './authority.mjs';
import {stageUnlock} from './state.mjs';
import {scanAmounts} from './scans.mjs';
import {issueOtp,verifyOtp} from './kit.mjs';
export const activeCaptures=j=>j.captures.filter(c=>!c.superseded);
export function nextStage(s){const j=s.job;if(!j?.approved)return null;return j.approved.stages.find(stage=>activeCaptures(j).filter(c=>c.stageKey===stage.key).length<stage.shots)||null;}
export function stageTime(s,stage){return stageUnlock(s.job.approved.stages,s.job.captures,s.job.approved.stages.findIndex(t=>t.key===stage.key));}
function actor(a,expected){requireRule(a===expected,'ACTOR_BLOCK',`${expected} owns this action`);}
function distance(a,b){const rad=x=>x*Math.PI/180;const dlat=rad(a.lat-b.lat),dlng=rad(a.lng-b.lng);return 6371000*2*Math.asin(Math.sqrt(Math.sin(dlat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dlng/2)**2));}
export function evaluateGate(s,final=true){const j=s.job,cs=activeCaptures(j),amounts=scanAmounts(j);const valid=j.scans.filter(r=>['VALID','VALID_EXTRA'].includes(r.outcome));const issues=j.scans.filter(r=>r.issue?.status==='OPEN');const points=[...valid,...cs];const near=points.filter(r=>distance(r.location,j.site)+r.location.accuracy<=150).length;const onSite=points.length>0&&near/points.length>=.9&&points.every(r=>distance(r.location,j.site)<=1000&&r.location.accuracy<=100);const ordered=j.approved.stages.every((stage,i)=>{const shots=cs.filter(c=>c.stageKey===stage.key);return shots.length>=stage.shots&&shots.every(c=>c.at>=stageUnlock(j.approved.stages,cs,i)&&c.assessment?.status==='PASS'&&(!stage.challenge_code||c.assessment.challengeConfirmed));});const start=cs.find(c=>j.approved.stages.find(t=>t.key===c.stageKey)?.flood_pair_role==='START'),end=cs.find(c=>j.approved.stages.find(t=>t.key===c.stageKey)?.flood_pair_role==='END');const flood=!j.approved.stages.some(t=>t.flood_pair_role)||!!(start&&end&&end.at-start.at>=1440*60000&&end.assessment?.floodResult==='PASS');const missingShots=j.approved.stages.reduce((n,t)=>n+Math.max(0,t.shots-cs.filter(c=>c.stageKey===t.key).length),0),pendingReview=cs.filter(c=>!c.assessment).length,failedReview=cs.filter(c=>c.assessment?.status==='FAIL').length;
 const stageProblems=[];
 if(missingShots)stageProblems.push(missingShots+' missing stage photos. Record the remaining stages before requesting handover.');
 if(pendingReview)stageProblems.push(pendingReview+' stage photos await reviewer assessment.');
 if(failedReview)stageProblems.push(failedReview+' stage photos failed review; request redo and record replacement evidence.');
 if(cs.some(c=>c.duplicateOf))stageProblems.push('Duplicate images require fresh captures.');
 if(j.approved.stages.some((stage,i)=>cs.some(c=>c.stageKey===stage.key&&c.at<stageUnlock(j.approved.stages,cs,i))))stageProblems.push('Recorded stage order or curing gaps need correction.');
 if(j.approved.stages.some(stage=>stage.challenge_code&&cs.some(c=>c.stageKey===stage.key&&c.assessment?.status==='PASS'&&!c.assessment.challengeConfirmed)))stageProblems.push('The reviewer must confirm each required visible challenge code.');
 if(start&&end&&end.at-start.at<1440*60000)stageProblems.push('The paired flood test must span at least 24 hours.');
 if(start&&end&&end.assessment?.status==='PASS'&&end.assessment.floodResult!=='PASS')stageProblems.push('The reviewer must confirm a passing paired flood-test result.');
 const rows=[
 ['Genuine, unused packs',valid.length>0&&!issues.length&&!j.scans.some(r=>r.outcome==='PROVISIONAL'),'Every credited pack is registered; unresolved rejected packs block issuance.'],
 ['Correct system products',j.approved.bom.every(b=>valid.some(r=>r.sku===b.sku&&r.unit===b.unit))&&!issues.some(r=>r.outcome==='WRONG_SKU'),'Each approved SKU must be present.'],
 ['Coverage quantity',j.approved.bom.every(b=>(amounts[b.sku]||0)>=b.required*(1-b.quantityTolerance)&&(amounts[b.sku]||0)<=Math.max(b.purchased,b.required*(1+b.quantityTolerance))),'Within frozen quote tolerance and necessary pack rounding; units stay separate.'],
 ['On-site evidence',onSite,'At least 90% conservatively inside 150 m; no distant or inaccurate evidence.'],
 ['Ordered work and curing',ordered&&flood&&!cs.some(c=>c.duplicateOf),stageProblems.length?stageProblems.join(' '):'All required photos passed review, with visible challenges and a passing 24-hour paired flood test.'],
 ['Homeowner confirmations',!!j.otps.START?.verified&&!j.handoverHold&&(!final||!!j.otps.CLOSE?.verified),!j.otps.START?.verified?'Verify the homeowner start code first.':j.handoverHold?'Start verified; resolve the homeowner concern before a fresh closing confirmation.':!final?'Start verified; closing code follows the first five checks.':j.otps.CLOSE?.verified?'Start and closing codes verified.':!ordered||!flood||cs.some(c=>c.duplicateOf)?'Start verified. Finish stage evidence review before requesting the closing code.':!j.otps.CLOSE?'Start verified. Request the homeowner closing code, then confirm handover.':'Start verified. Enter the requested homeowner closing code to confirm handover.']
 ];return rows.map(([name,pass,reason],i)=>({number:i+1,name,pass:!!pass,reason,evidenceRefs:i<3?valid.map(r=>r.id):i===3?points.map(r=>r.id):i===4?cs.map(c=>c.id):['START','CLOSE'].filter(k=>j.otps[k]?.verified).map(k=>({purpose:k,verifiedAt:j.otps[k].verifiedAt}))}));}

// Derived from current evidence on every response; never persist a stale readiness snapshot.
export function handoverReadiness(s){
 const j=s.job;if(!j?.approved)return null;
 const cs=activeCaptures(j),checks=evaluateGate(s,true),preclose=evaluateGate(s,false);
 const missingShots=j.approved.stages.reduce((n,t)=>n+Math.max(0,t.shots-cs.filter(c=>c.stageKey===t.key).length),0);
 const pendingReview=cs.filter(c=>!c.assessment).length,failedReview=cs.filter(c=>c.assessment?.status==='FAIL').length;
 const blockers=[];
 if(missingShots)blockers.push(`Record ${missingShots} missing stage photo${missingShots===1?'':'s'} in order, including the paired flood test.`);
 if(pendingReview)blockers.push(`Have the reviewer assess ${pendingReview} pending stage photo${pendingReview===1?'':'s'}.`);
 if(failedReview)blockers.push(`Have the reviewer request redo for ${failedReview} failed stage photo${failedReview===1?'':'s'}, then record and review the replacement evidence.`);
 for(const check of preclose.slice(0,4))if(!check.pass)blockers.push(`Clear check ${check.number}: ${check.name}. ${check.reason}`);
 if(!preclose[4].pass&&!missingShots&&!pendingReview&&!failedReview)blockers.push('Have the reviewer resolve stage order, curing, visible challenge codes, duplicate images or the paired flood-test result.');
 if(!j.otps.START?.verified)blockers.push('Verify the homeowner start code before handover.');
 if(j.handoverHold)blockers.push('Have operations resolve the homeowner concern, then obtain a fresh closing confirmation.');
 const eligible=['IN_PROGRESS','REVIEW','HANDOVER'].includes(j.status);
 const canRequestClose=eligible&&preclose.every(c=>c.pass)&&!j.otps.CLOSE?.verified;
 const canIssue=j.status==='HANDOVER'&&checks.every(c=>c.pass);
 return {checks,missingShots,pendingReview,failedReview,blockers,canRequestClose,canIssue,
  nextAction:j.certificate?'Completion record issued. Open Outcome.':blockers[0]||(canIssue?'All six checks pass. The reviewer can issue the Water Passport.':'Request the homeowner closing code, verify handover, then ask the reviewer to issue the Water Passport.')};
}
export const executionHandlers={
 REQUEST_CHALLENGE(s,p,a){actor(a,'applicator');const stage=nextStage(s);requireRule(['IN_PROGRESS','REVIEW'].includes(s.job.status)&&stage?.key===p.stageKey,'STAGE_ORDER','Capture the next incomplete stage');s.job.challenge={stageKey:stage.key,code:randomUUID().slice(0,6).toUpperCase(),expires:s.clock.now+15*60000};},
 CAPTURE_STAGE(s,p,a){actor(a,'applicator');const j=s.job,stage=nextStage(s);requireRule(['IN_PROGRESS','REVIEW'].includes(j?.status)&&stage?.key===p.stageKey,'STAGE_ORDER','Stages must be captured in order');requireRule(s.clock.now>=stageTime(s,stage),'CURING_GAP','The curing gap is still running');const amounts=scanAmounts(j);requireRule(j.approved.bom.every(line=>amounts[line.sku]>0)&&(stage.skus||[]).every(sku=>amounts[sku]>0),'STAGE_PRODUCTS','Scan the required stage products first');requireRule(['camera','sample'].includes(p.mode),'CAMERA_ONLY','Capture using the app camera or an explicitly labelled sample');requireRule(p.location&&Number.isFinite(p.location.lat)&&Number.isFinite(p.location.lng)&&Number.isFinite(p.location.accuracy)&&p.location.accuracy>0,'PHOTO_LOCATION','Location with accuracy is required');if(stage.challenge_code)requireRule(j.challenge?.stageKey===stage.key&&j.challenge.expires>s.clock.now&&p.challengeCode===j.challenge.code,'CHALLENGE_REQUIRED','Request a current stage code and place it in the frame');requireRule(p.mode==='sample'||/^data:image\/jpeg;base64,/.test(p.image||''),'PHOTO_REQUIRED','Capture a JPEG with the live camera');const image=p.mode==='sample'?`sample:${j.id}:${stage.key}:${j.captures.length}`:p.image;const hash=createHash('sha256').update(image).digest('hex');const duplicate=j.captures.find(c=>c.hash===hash);j.captures.push({id:randomUUID(),stageKey:stage.key,at:s.clock.now,receivedAt:Date.now(),mode:p.mode,image:p.mode==='sample'?null:image,hash,location:p.location,challengeCode:stage.challenge_code?p.challengeCode:null,duplicateOf:duplicate?.id||null,assessment:null,weatherAcknowledged:!!p.weatherAcknowledged,productSerials:j.scans.filter(r=>['VALID','VALID_EXTRA'].includes(r.outcome)).map(r=>r.serial)});j.status='IN_PROGRESS';},
 NEXT_CURE(s,p,a){actor(a,'presenter');const stage=nextStage(s);requireRule(stage,'NO_STAGE','All stages captured');const at=stageTime(s,stage);requireRule(Number.isFinite(at),'STAGE_ORDER','Finish the preceding stage first');const delta=Math.max(0,at-s.clock.now);s.clock.now+=delta;s.clock.offset+=delta;},
 ASSESS_CAPTURE(s,p,a){actor(a,'admin');requireRule(!s.job?.certificate,'ISSUED_JOB','Issued evidence cannot be rewritten');const c=s.job.captures.find(c=>c.id===p.captureId&&!c.superseded);requireRule(c,'PHOTO_UNKNOWN','Photo is no longer current');requireRule(['PASS','FAIL'].includes(p.status)&&String(p.reason||'').length>=15,'REVIEW_REASON','Record an assessment and detailed reason');const stage=s.job.approved.stages.find(t=>t.key===c.stageKey);requireRule(p.status!=='PASS'||!c.duplicateOf,'DUPLICATE_PHOTO','Identical image bytes require a new capture');requireRule(p.status!=='PASS'||!stage.challenge_code||p.challengeConfirmed===true,'CHALLENGE_REVIEW','Confirm that the code is visibly present; metadata alone is insufficient');if(stage.flood_pair_role==='END'&&p.status==='PASS')requireRule(p.floodResult==='PASS','FLOOD_REVIEW','Record the flood-test result');c.assessment={status:p.status,reason:p.reason,challengeConfirmed:!!p.challengeConfirmed,floodResult:p.floodResult||null,at:s.clock.now};s.job.reviews.push({id:randomUUID(),type:'PHOTO',captureId:c.id,...c.assessment});},
 REDO_STAGE(s,p,a){actor(a,'admin');requireRule(['IN_PROGRESS','REVIEW','HANDOVER'].includes(s.job?.status),'REDO_STATE','Only active work can be reopened');requireRule(!s.job.certificate,'ISSUED_JOB','Issued proof cannot be rewritten');const stages=s.job.approved.stages,index=stages.findIndex(t=>t.key===p.stageKey);requireRule(index>=0&&String(p.reason||'').length>=15,'REDO_REASON','Choose a stage and explain the redo');const keys=stages.slice(index).map(t=>t.key);s.job.captures.filter(c=>keys.includes(c.stageKey)&&!c.superseded).forEach(c=>{c.superseded=true;c.redoReason=p.reason;});s.job.status='IN_PROGRESS';s.job.otps.CLOSE=null;s.job.reviews.push({id:randomUUID(),type:'REDO',reason:p.reason,stageKey:p.stageKey,at:s.clock.now});},
 EVALUATE_GATE(s,p,a){actor(a,'admin');requireRule(['IN_PROGRESS','REVIEW','HANDOVER'].includes(s.job?.status),'GATE_STATE','Started jobs only');const checks=evaluateGate(s,true),pass=checks.every(c=>c.pass);s.job.gateRuns.push({id:randomUUID(),checks,pass,preclose:!s.job.otps.CLOSE?.verified,at:s.clock.now});s.job.status=pass||checks.slice(0,5).every(c=>c.pass)&&s.job.otps.START?.verified?'HANDOVER':'REVIEW';settleBase(s,checks);},
 REQUEST_CLOSE(s,p,a){actor(a,'applicator');requireRule(['IN_PROGRESS','REVIEW','HANDOVER'].includes(s.job?.status)&&evaluateGate(s,false).every(c=>c.pass),'CLOSE_GATE','First clear the five proof checks and start confirmation. '+(handoverReadiness(s)?.blockers.join(' ')||'Complete the current evidence review.'));issueOtp(s,'CLOSE');s.job.status='HANDOVER';},
 VERIFY_CLOSE(s,p,a){actor(a,'applicator');requireRule(s.job?.status==='HANDOVER','OTP_STATE','Job is not ready for handover');verifyOtp(s,p,'CLOSE');},
 ISSUE_PASSPORT(s,p,a){actor(a,'admin');if(s.job?.certificate)return;requireRule(s.job?.status==='HANDOVER'&&evaluateGate(s,true).every(c=>c.pass),'WARRANTY_GATE','All six checks must pass before issuance');const j=s.job;j.certificate={number:'DEMO-WP-'+randomUUID().slice(0,8).toUpperCase(),token:randomUUID(),status:'ACTIVE_DEMO',issuedAt:s.clock.now,proofId:null,proofAnchor:'ISSUANCE_EVENT',jobCode:j.code,system:j.approved.packageName,area:j.approved.area.treated,validity:'Illustrative terms; no active warranty',synthetic:true};j.status='COMPLETED';settleBase(s,evaluateGate(s,true));if(!j.reviews.some(r=>r.type==='REDO'||r.type==='PHOTO'&&r.status==='FAIL')&&!j.gateRuns.some(g=>g.checks.slice(0,5).some(c=>!c.pass)||!g.preclose&&!g.pass))s.points.push({id:randomUUID(),jobId:j.id,key:'first-pass:'+j.id,amount:50,availableDelta:50,heldDelta:0,status:'RELEASED',at:s.clock.now});message(s,'passport','Your completion record is ready. Review the recorded work and rate your experience.',{certificate:structuredClone(j.certificate)});},
 VOID_PASSPORT(s,p,a){actor(a,'admin');requireRule(s.job?.certificate&&String(p.reason||'').length>=15,'VOID_REASON','An issued certificate and detailed reason are required');s.job.certificate.status='VOID_DEMO';s.job.certificate.voidReason=p.reason;s.job.certificate.voidedAt=s.clock.now;if(!s.points.some(r=>r.key==='void:'+s.job.id)){const released=s.points.filter(r=>r.jobId===s.job.id&&r.status==='RELEASED').reduce((n,r)=>n+r.amount,0);s.points.push({id:randomUUID(),jobId:s.job.id,key:'void:'+s.job.id,amount:-released,availableDelta:-released,heldDelta:0,status:'REVERSED',at:s.clock.now});}},
 RATE_JOB(s,p,a){actor(a,'homeowner');requireRule(s.job?.certificate&&Number.isInteger(p.rating)&&p.rating>=1&&p.rating<=5,'RATING_REQUIRED','Rate a completed job from 1 to 5');requireRule(!s.job.rating,'RATING_EXISTS','A rating has already been recorded');s.job.rating={value:p.rating,comment:String(p.comment||'').slice(0,500),at:s.clock.now};message(s,'thanks','Thank you. Your rating has been recorded.');},
 REPORT_PAYMENT(s,p,a){actor(a,'applicator');requireRule(s.job?.certificate&&Number.isInteger(p.amountPaise)&&p.amountPaise>0&&p.amountPaise<=s.job.approved.totalPaise,'PAYMENT_AMOUNT','Report a payment up to the approved job value');requireRule(!s.payments.some(r=>r.jobId===s.job.id),'PAYMENT_EXISTS','Payment already recorded');s.payments.push({id:randomUUID(),jobId:s.job.id,amountPaise:p.amountPaise,status:'REPORTED',route:'Paid directly; not provider verified',at:s.clock.now});}
};








