import {randomUUID}from 'node:crypto';
import {requireRule,message}from './authority.mjs';
import {leadHandlers}from './leads.mjs';
import {recordScan}from './scans.mjs';
const customer={name:'Ananya Rao',phone:'DEMO-0001',city:'Bengaluru',address:'Indiranagar, Bengaluru'};
export const journeyHandlers={
 ADMIN_REOFFER(s,p,a){requireRule(a==='admin'&&!s.job&&['DECLINED','EXPIRED'].includes(s.offer?.status),'OFFER_STATE','Only an unassigned closed offer can be re-offered');requireRule(s.profile.status==='CERTIFIED'&&s.profile.loggedIn,'NOT_ELIGIBLE','The assigned applicator must be certified and signed in');requireRule(String(p.reason||'').trim().length>=15,'OFFER_REASON','Record why this visit is being re-offered');s.offer={...s.offer,status:'OFFERED',candidate:s.profile.id,deadline:s.clock.now+900000,reofferReason:p.reason};message(s,'booking','Operations has reopened your visit request with the eligible applicator. Acceptance is pending.');},
 RESUME_MESSAGES(s,p,a){requireRule(a==='homeowner'&&s.customer,'CONSENT_STATE','An existing customer is required');s.customer.messagingStopped=false;if(s.presentation?.step==='STOPPED')s.presentation.step='CONSENT';message(s,'permission','Service updates resumed at your request. Marketing permission remains separate.');},
 DEALER_SHORTAGE(s,p,a){requireRule(a==='dealer'&&s.job?.kit?.status==='REQUESTED','SHORTAGE_STATE','Flag a shortage before marking the kit ready');requireRule(String(p.reason||'').trim().length>=8,'SHORTAGE_REASON','Describe the unavailable product or pack');s.job.kit.shortage={status:'OPEN',reason:p.reason,at:s.clock.now};message(s,'supply','The dealer has flagged material availability. Operations will coordinate; no product substitution has been approved.');},
 RESOLVE_SHORTAGE(s,p,a){requireRule(a==='admin'&&s.job?.kit?.shortage?.status==='OPEN','SHORTAGE_STATE','No open dealer shortage');requireRule(String(p.reason||'').trim().length>=15,'SHORTAGE_REASON','Record how the approved material availability was restored');s.job.kit.shortage={...s.job.kit.shortage,status:'RESOLVED',resolution:p.reason,at:s.clock.now};},
 START_STORY(s,p,a){requireRule(a==='presenter'&&!s.job&&!s.lead,'STORY_EXISTS','Start a fresh presentation to preserve the existing job');s.profile.loggedIn=true;s.presentation={version:1,step:'CONSENT',context:{...customer,problem:'Terrace leakage during rain',photos:['wide-view','damage','drain']},serviceConsent:false,safety:null,slot:null,care:null};s.customer={...customer,marketingConsent:false,messagingStopped:false};message(s,'website','I need help with terrace leakage during rain.',{direction:'outgoing'});message(s,'enquiry','Hi Ananya. You shared your terrace photos and address on our website. I have those details. May we send service updates about this enquiry, visit and work here? Marketing needs separate permission.');},
 ENQUIRY_REPLY(s,p,a){requireRule(a==='homeowner'&&s.presentation&&!s.job&&!s.lead,'ENQUIRY_STATE','This enquiry is not awaiting a reply');const c=s.presentation;requireRule(!s.customer.messagingStopped,'MESSAGES_STOPPED','Service updates have been stopped');const v=String(p.value||'');if(c.step==='CONSENT'){requireRule(['YES','NO'].includes(v),'CONSENT_CHOICE','Choose service permission');if(v==='NO'){s.customer.messagingStopped=true;c.step='STOPPED';return;}c.serviceConsent=true;c.step='SAFETY';message(s,'reply','Yes, service updates.',{direction:'outgoing'});message(s,'triage','Before we book the visit: are cracks widening, is concrete sagging, or is steel exposed? Photos help prepare the visit; the final diagnosis happens on site.');}else if(c.step==='SAFETY'){requireRule(['HAIRLINE','STRUCTURAL'].includes(v),'SAFETY_CHOICE','Choose the reported site condition');c.safety=v;message(s,'reply',v==='HAIRLINE'?'Hairline cracks only.':'Major cracks or sagging.',{direction:'outgoing'});if(v==='STRUCTURAL'){c.step='BLOCKED';message(s,'triage','Please arrange a qualified structural inspection before waterproofing. An advisor will follow up; no system is being recommended.');c.support={status:'OPEN',reason:'Structural concern reported before booking',owner:'Technical reviewer'};}else{c.step='SLOT';message(s,'booking-options','Let’s arrange an inspection. Ravi can visit tomorrow, 10 am–12 pm or 2 pm–4 pm. Which works for you?');}}else if(c.step==='SLOT'){requireRule(['Tomorrow · 10 am–12 pm','Tomorrow · 2 pm–4 pm'].includes(v),'SLOT_CHOICE','Choose an available slot');c.slot=v;c.step='ADDRESS';message(s,'reply',v,{direction:'outgoing'});message(s,'address','Please confirm the website address: Indiranagar, Bengaluru. It will be shared with the assigned applicator after acceptance.');}else if(c.step==='ADDRESS'){requireRule(v==='CONFIRM','ADDRESS_CONFIRM','Confirm the visit address');leadHandlers.OFFER_LEAD(s,{},'presenter');s.lead.customer={...customer};s.lead.slot=c.slot;s.lead.problem=c.context.problem;s.lead.photos=c.context.photos;s.lead.triage='Reported hairline cracks and rain-related leakage; final diagnosis pending';c.step='BOOKED';message(s,'booking','Your visit request is booked. We’ll introduce Ravi once he accepts. The address and photos travel with this enquiry.');}else requireRule(false,'ENQUIRY_STATE','This enquiry is not awaiting a reply');},
 INJECT_WRONG_SKU(s,p,a){requireRule(a==='presenter'&&s.job?.status==='IN_PROGRESS','SCAN_STATE','Start the job before showing a product exception');requireRule(!s.job.scans.some(x=>x.outcome==='WRONG_SKU'),'EXCEPTION_EXISTS','This job already records a wrong product');const expected=s.job.approved.bom.find(b=>b.sku==='WPM810')||s.job.approved.bom[0];const pack=Object.values(s.registry).find(r=>!r.consumedBy&&!s.job.approved.bom.some(b=>b.sku===r.sku));requireRule(pack,'STOCK','No sample wrong product available');const scan=recordScan(s,{serial:pack.serial,location:{...s.job.site,accuracy:12,mode:'sample'}});scan.issue.expectedSku=expected.sku;message(s,'exception','A product mismatch was found before use. Ravi will request the correct pack. The rejected pack cannot count towards your approved system.');},
 REQUEST_REPLACEMENT(s,p,a){requireRule(a==='applicator'&&['IN_PROGRESS','REVIEW'].includes(s.job?.status),'REPLACEMENT_STATE','A started job is required');const scan=s.job.scans.find(x=>x.id===p.scanId);requireRule(scan?.issue?.status==='OPEN','SCAN_ISSUE','Choose an unresolved rejected pack');const line=s.job.approved.bom.find(b=>b.sku===p.sku),size=Number(p.size);requireRule(line?.packs.some(x=>x.size===size),'REPLACEMENT_SKU','Choose an approved SKU and pack size');requireRule(!scan.issue.expectedSku||scan.issue.expectedSku===line.sku,'REPLACEMENT_SKU','Replacement must match the expected system product');requireRule(!scan.issue.request,'REPLACEMENT_EXISTS','Replacement already requested');scan.issue.expectedSku=line.sku;scan.issue.request={id:randomUUID(),sku:line.sku,size,unit:line.unit,status:'REQUESTED',at:s.clock.now,dealerId:s.job.kit.dealerId};message(s,'correction','Ravi has requested the correct product from '+s.job.kit.dealerName+'. Work clearance remains pending until the correction is recorded.');},
 SUPPLY_REPLACEMENT(s,p,a){requireRule(a==='dealer','ACTOR_BLOCK','The tagged dealer supplies replacements');const scan=s.job?.scans.find(x=>x.id===p.scanId),r=scan?.issue?.request;requireRule(scan?.issue.status==='OPEN'&&r?.status==='REQUESTED','REPLACEMENT_STATE','No replacement is awaiting supply');const pack=s.registry[p.serial];requireRule(pack&&!pack.consumedBy&&(!pack.reservedFor||pack.reservedFor===s.job.id)&&pack.sku===r.sku&&pack.size===r.size&&pack.unit===r.unit,'REPLACEMENT_PACK','Use an unused registry pack matching the requested SKU and size');pack.reservedFor=s.job.id;r.serial=pack.serial;r.status='READY';r.readyAt=s.clock.now;message(s,'correction','The correct replacement pack is ready at '+s.job.kit.dealerName+'. Ravi will scan it on site and the supervisor will review the correction.');},
 ACK_PAYMENT(s,p,a){requireRule(a==='homeowner'&&s.job?.status==='COMPLETED','PAYMENT_STATE','Complete the job before recording payment acknowledgement');requireRule(['PAID','PENDING'].includes(p.status),'PAYMENT_STATUS','Choose a payment status');requireRule(!s.job.receiptConfirmed,'PAYMENT_LOCKED','A confirmed receipt cannot be overwritten');s.job.customerPayment={status:p.status,amountPaise:p.status==='PAID'?s.job.approved.totalPaise:0,at:s.clock.now};message(s,'payment',p.status==='PAID'?'Payment reported by the homeowner. Ravi must confirm receipt; this is not provider-verified payment.':'Payment is pending. Your completion record remains available.');},
 CONFIRM_RECEIPT(s,p,a){requireRule(a==='applicator'&&s.job?.customerPayment?.status==='PAID','PAYMENT_STATE','Homeowner payment acknowledgement is required');requireRule(!s.job.receiptConfirmed,'PAYMENT_EXISTS','Receipt already confirmed');const existing=s.payments.find(x=>x.jobId===s.job.id);requireRule(!existing||existing.amountPaise===s.job.customerPayment.amountPaise,'PAYMENT_MISMATCH','Reported payment amounts must match before recipient confirmation');s.job.receiptConfirmed={at:s.clock.now,amountPaise:s.job.customerPayment.amountPaise};if(existing){existing.status='ACKNOWLEDGED';existing.route='Direct payment; two-party acknowledgement, not provider verified';}if(!existing)s.payments.push({id:randomUUID(),jobId:s.job.id,amountPaise:s.job.customerPayment.amountPaise,status:'ACKNOWLEDGED',route:'Direct payment; two-party acknowledgement, not provider verified',at:s.clock.now});message(s,'payment','Ravi has confirmed receipt of your direct payment. Both acknowledgements are recorded.');},
 CARE_CHOICE(s,p,a){requireRule(a==='homeowner'&&s.job?.status==='COMPLETED','CARE_STATE','Aftercare follows completion');requireRule(typeof p.enabled==='boolean','CARE_CHOICE','Choose an aftercare preference');s.job.care={enabled:p.enabled,at:s.clock.now,deliveryStatus:'NOT_SCHEDULED'};message(s,'care',p.enabled?'Your pre-monsoon reminder preference is recorded. Scheduling is not connected yet. No promotional permission has been added.':'No annual reminder will be sent. Your work record and support remain available.');},
 REQUEST_SUPPORT(s,p,a){requireRule(a==='homeowner'&&s.customer,'SUPPORT_STATE','An active customer is required');requireRule(String(p.reason||'').trim().length>=8,'SUPPORT_REASON','Describe what needs attention');const target=s.job||s.presentation;if(s.job&&!s.job.certificate&&['IN_PROGRESS','REVIEW','HANDOVER'].includes(s.job.status)){s.job.handoverHold=true;s.job.otps.CLOSE=null;if(s.job.status==='HANDOVER')s.job.status='REVIEW';}target.support={status:'OPEN',reason:p.reason.trim().slice(0,500),owner:'Operations administrator',at:s.clock.now};message(s,'support','Your concern is attached to this work record for an advisor. Handover is not accepted by this message.');},
 RESOLVE_SUPPORT(s,p,a){requireRule(a==='admin','ACTOR_BLOCK','Admin handles support');const target=s.job||s.presentation;requireRule(target?.support?.status==='OPEN'&&String(p.reason||'').trim().length>=15,'SUPPORT_REASON','Record the action taken to resolve this concern');if(s.job)s.job.handoverHold=false;target.support={...target.support,status:'RESOLVED',resolution:p.reason,reviewedAt:s.clock.now};message(s,'support','An advisor recorded the response to your concern: '+p.reason);},
 RECORD_INVOICE(s,p,a){requireRule(a==='dealer'&&s.job?.kit&&s.job.kit.status==='READY','INVOICE_STATE','A ready tagged kit is required');requireRule(!s.job.kit.invoice,'INVOICE_EXISTS','Invoice already recorded');requireRule(String(p.number||'').trim().length>=3&&Number.isSafeInteger(p.amountPaise)&&p.amountPaise>0&&p.amountPaise<=100000000,'INVOICE_INPUT','Record an invoice reference and positive material amount');s.job.kit.invoice={number:p.number.trim().slice(0,100),amountPaise:p.amountPaise,status:'DECLARED',at:s.clock.now};},
 RECONCILE_INVOICE(s,p,a){requireRule(a==='admin'&&s.job?.kit?.invoice?.status==='DECLARED','INVOICE_STATE','An unreconciled declared invoice is required');requireRule(String(p.reason||'').trim().length>=15,'INVOICE_REASON','Record the invoice evidence you reviewed');s.job.kit.invoice={...s.job.kit.invoice,status:'RECONCILED',reason:p.reason,reviewedAt:s.clock.now};}
};
export function syncJourney(s,type,p){if(type==='CANCEL_JOB')for(const pack of Object.values(s.registry))if(pack.reservedFor===s.job.id)delete pack.reservedFor;if(!s.presentation)return;const j=s.job;
 if(type==='ACCEPT_LEAD'){s.customer={...s.customer,...s.presentation.context,serviceConsent:s.presentation.serviceConsent};message(s,'assignment','Ravi accepted your visit for '+s.presentation.slot+'. Your address and reference photos are attached.');}
 if(type==='CHECK_IN')message(s,'visit','Ravi has checked in for your inspection. He will confirm the site condition and measurement.');
 if(type==='SAVE_DIAGNOSIS')message(s,'diagnosis','Inspection recorded: '+j.diagnosis.area.treated+' sq ft treated area. '+(j.diagnosis.analysis.blocking||'Review the proposed system and scope before approving.'));
 if(type==='TAG_DEALER')message(s,'supply','Your approved material request is with '+j.kit.dealerName+'. No product substitution has been authorised.');
 if(type==='READY_KIT')message(s,'supply','The dealer has marked your approved kit ready. Share the start code only when you agree work can begin.');
 if(type==='CAPTURE_STAGE'){const t=j.approved.stages.find(t=>t.key===p.stageKey);message(s,'progress',t.name+' recorded. Technical review is pending; recorded photos alone do not establish a pass.');}
 if(type==='RESOLVE_SCAN')message(s,'correction','The supervisor recorded removal of the rejected product and its eligible scanned replacement. The original rejection remains in the job history.');
 if(type==='RATE_JOB'&&j.rating.value<4)j.support={status:'OPEN',reason:'Low customer rating: '+j.rating.value+' / 5. '+j.rating.comment,owner:'Operations administrator',at:s.clock.now};
 if(type==='ISSUE_PASSPORT')message(s,'aftercare','Keep your completion record. You can report a concern, acknowledge direct payment, rate the work and choose optional annual care.');
}
