import {randomInt}from 'node:crypto';import {requireRule,message}from './authority.mjs';
export function issueOtp(s,purpose){const old=s.job.otps[purpose];requireRule(!old||s.clock.now-old.sentAt>=60000,'OTP_COOLDOWN','Wait one demo minute before resending');const recent=(s.job.otpRequests||[]).filter(at=>s.clock.now-at<3600000);requireRule(recent.length<3,'OTP_RESEND_LIMIT','Three codes per demo hour; advance time or contact review');s.job.otpRequests=[...recent,s.clock.now];s.job.otps[purpose]={purpose,jobId:s.job.id,code:String(randomInt(100000,1000000)),sentAt:s.clock.now,expires:s.clock.now+1800000,attempts:0,verified:false};message(s,'otp',`${purpose==='START'?'Start':'Handover'} confirmation code. Share it only when you are ready.`,{purpose,code:s.job.otps[purpose].code,jobId:s.job.id});}
export function verifyOtp(s,p,purpose){const otp=s.job.otps[purpose];requireRule(p.jobId===s.job.id&&p.purpose===purpose,'OTP_PURPOSE','Code belongs to a different job or purpose');requireRule(otp&&!otp.verified,'OTP_USED','Request a current unused code');requireRule(s.clock.now<otp.expires,'OTP_EXPIRED','Code expired. Request a new code');requireRule(otp.attempts<5,'OTP_LOCKED','Five failed attempts; request a new code');if(p.code!==otp.code){otp.attempts++;s.job.lastOtpError=otp.attempts>=5?'Five failed attempts; request a new code':'Incorrect code; '+(5-otp.attempts)+' attempts remain';return false;}otp.verified=true;otp.verifiedAt=s.clock.now;s.job.lastOtpError=null;return true;}
export const kitHandlers={
 TAG_DEALER(s,p,a){requireRule(a==='applicator'&&s.job?.status==='APPROVED','KIT_STATE','Approve the quote before the dealer handoff');requireRule(p.dealerId==='dealer-001','DEALER_UNKNOWN','Choose the tagged demo dealer');if(s.job.kit)return;s.job.kit={dealerId:p.dealerId,dealerName:'Akshaya Building Supplies',status:'REQUESTED',bom:structuredClone(s.job.approved.bom),quoteId:s.job.approved.quoteId,sentAt:s.clock.now,simulatedOrder:true};},
 READY_KIT(s,p,a){requireRule(a==='dealer'&&s.job?.kit,'KIT_STATE','Dealer handoff required');requireRule(s.job.kit.shortage?.status!=='OPEN','KIT_SHORTAGE','Resolve the dealer shortage before marking readiness');if(s.job.status==='KIT_READY')return;requireRule(s.job.status==='APPROVED','KIT_STATE','Kit cannot be changed after start');s.job.kit.status='READY';s.job.kit.readyAt=s.clock.now;s.job.status='KIT_READY';issueOtp(s,'START');},
 REQUEST_OTP(s,p,a){requireRule(a==='applicator','ACTOR_BLOCK','Applicator requests the homeowner code');requireRule(p.purpose==='START'&&s.job?.status==='KIT_READY','OTP_STATE','Start code requires a ready kit');issueOtp(s,'START');},
 VERIFY_START(s,p,a){requireRule(a==='applicator'&&s.job?.status==='KIT_READY','OTP_STATE','Job is not waiting for start');if(verifyOtp(s,p,'START')){s.job.status='IN_PROGRESS';s.job.startedAt=s.clock.now;message(s,'start','Work has started. Genuine sample pack scans and stage evidence will be recorded before handover.');}}
};
