import {randomUUID}from 'node:crypto';import {requireRule,message,foundationHandlers}from './authority.mjs';import {fixtures}from '../data/fixtures.mjs';import {eligible}from './profile.mjs';
export function createJob(s,fixture,mode){const homeownerId=randomUUID(),leadId=s.lead?.id||randomUUID(),jobId=randomUUID();s.customer={...structuredClone(fixture.customer),id:homeownerId,marketingConsent:false,messagingStopped:false};s.job={id:jobId,code:'PRO-'+jobId.slice(0,6).toUpperCase(),leadId,homeownerId,applicatorId:s.profile.id,mode,status:'VISIT_BOOKED',areaType:fixture.areaType,site:fixture.location,attribution:mode==='ardex'?structuredClone(s.lead.attribution):{source:'my-lead',marketingConsent:false,synthetic:true},diagnosis:null,quotes:[],approved:null,kit:null,otps:{},scans:[],captures:[],gateRuns:[],reviews:[],certificate:null,rating:null};}
function reroute(s,reason){s.offer.status=reason;s.offer.closedAt=s.clock.now;s.offer.nextCandidate='app-demo-next';s.offer.reassignment={status:'OFFERED',candidate:'app-demo-next',deadline:s.clock.now+900000};s.notices.push({text:'Offer '+reason.toLowerCase()+'; routed to the next eligible demo applicator.'});}
export const leadHandlers={
 OFFER_LEAD:(s,p,a)=>{requireRule(a==='presenter','ACTOR_BLOCK','Presenter seeds the booking');requireRule(!s.job&&!s.lead,'LEAD_EXISTS','Reset the scenario before a new booking');requireRule(s.scenario==='terrace','SCENARIO_MODE','Ardex booking is the terrace scenario');const f=fixtures.terrace;s.lead={id:randomUUID(),customer:structuredClone(f.customer),city:'BLR',areaType:f.areaType,slot:'Today, 10:00–11:00',problem:'Terrace seepage after rain',photos:['Sample wide view','Sample drain'],triage:'Initial AI triage: exposed terrace; confirm on site',site:f.location,attribution:{source:'ardex',campaign:'CHLEAR Peace of Mind · demo',ctwaClickId:'DEMO-CTWA-001',marketingConsent:false,synthetic:true}};s.offer={id:randomUUID(),candidate:s.profile.id,status:'OFFERED',deadline:s.clock.now+900000};},
 ACCEPT_LEAD:(s,p,a)=>{requireRule(a==='applicator'&&eligible(s),'NOT_ELIGIBLE','Sign in with a certified Bengaluru demo profile');if(s.offer?.status==='ACCEPTED'&&s.job)return;requireRule(s.offer?.status==='OFFERED'&&s.clock.now<s.offer.deadline,'OFFER_EXPIRED','This offer is no longer available');requireRule(s.offer.candidate===s.profile.id,'NOT_ASSIGNED','Offer belongs to another applicator');createJob(s,fixtures.terrace,'ardex');s.offer.status='ACCEPTED';s.offer.jobId=s.job.id;message(s,'introduction',`${s.profile.name}, your certified demo applicator, has accepted the visit. ${s.lead.slot}.`,{jobId:s.job.id,profile:{name:s.profile.name,tier:s.profile.tier,certification:s.profile.status}});},
 DECLINE_LEAD:(s,p,a)=>{requireRule(a==='applicator','ACTOR_BLOCK','Applicator action');requireRule(s.offer?.status==='OFFERED','OFFER_CLOSED','Offer already closed');reroute(s,'DECLINED');},
 ADVANCE:(s,p,a)=>{foundationHandlers.ADVANCE(s,p,a);if(s.offer?.status==='OFFERED'&&s.clock.now>=s.offer.deadline)reroute(s,'EXPIRED');}
};
