import {randomUUID} from 'node:crypto';
import {requireRule,message} from './authority.mjs';
export const quoteHandlers={
 SEND_QUOTE(s,p,a){requireRule(a==='applicator'&&s.profile.loggedIn,'ACTOR_BLOCK','Signed-in applicator sends quotes');const j=s.job,plan=j?.plan;requireRule(plan,'PLAN_REQUIRED','Calculate the material plan first');if(j.status==='QUOTE_SENT'&&j.quotes.at(-1)?.planVersion===plan.version)return;requireRule(j.status==='DIAGNOSIS','QUOTE_STATE','Only a draft can be sent');requireRule(plan.content.diagnosisId===j.diagnosis.id&&plan.content.catalogVersion===s.catalog._meta.version,'STALE_PLAN','Recalculate against the current diagnosis and catalog');const q={id:randomUUID(),jobId:j.id,version:j.quotes.length+1,planVersion:plan.version,token:randomUUID(),status:'SENT',sentAt:s.clock.now,expiresAt:s.clock.now+15*86400000,options:structuredClone(plan.content.options),selectedPackageCode:plan.content.selectedPackageCode,catalogVersion:plan.content.catalogVersion,demo:true};j.quotes.push(q);j.status='QUOTE_SENT';message(s,'quote','Your waterproofing plan is ready. Compare the options and approve the scope you prefer.',{quoteId:q.id,token:q.token,version:q.version,jobId:j.id});},
 APPROVE_QUOTE(s,p,a){requireRule(a==='homeowner','ACTOR_BLOCK','The homeowner approves the quote');const j=s.job,q=j?.quotes.at(-1);requireRule(q&&q.id===p.quoteId&&q.token===p.token,'STALE_QUOTE','This quote link was superseded or is invalid');if(q.status==='APPROVED'){requireRule(j.approved.packageCode===p.packageCode,'ALREADY_APPROVED','Approved scope is frozen');return;}requireRule(j.status==='QUOTE_SENT'&&q.status==='SENT','QUOTE_STATE','Quote is not awaiting approval');requireRule(s.clock.now<q.expiresAt,'QUOTE_EXPIRED','Quote expired; ask for a refreshed proposal');const option=q.options.find(o=>o.packageCode===p.packageCode);requireRule(option,'OPTION_OWNERSHIP','Choose an option on this quote');j.approved={...structuredClone(option),quoteId:q.id,quoteVersion:q.version,approvedAt:s.clock.now,stages:structuredClone(option.packageSnapshot.stages)};q.status='APPROVED';q.approvedPackageCode=p.packageCode;q.approvedAt=s.clock.now;j.status='APPROVED';message(s,'approval',`Approved: ${option.packageName}. Your scope and price are now frozen.`,{jobId:j.id,quoteId:q.id});},
 REVISE_QUOTE(s,p,a){requireRule(a==='applicator'&&s.job?.status==='QUOTE_SENT','QUOTE_STATE','An approved job needs a change order, not a draft revision');s.job.quotes.at(-1).status='SUPERSEDED';s.job.status='DIAGNOSIS';},
 DECLINE_QUOTE(s,p,a){requireRule(a==='homeowner'&&s.job?.status==='QUOTE_SENT','QUOTE_STATE','No quote is awaiting response');const q=s.job.quotes.at(-1);requireRule(q.id===p.quoteId&&q.status==='SENT','STALE_QUOTE','Quote is no longer current');q.status='DECLINED';q.reason=String(p.reason||'Homeowner declined').slice(0,200);message(s,'decline','Quote declined. Your applicator can revise the proposal; no work has been approved.');}
};

