import {holdPack}from './rewards.mjs';
import {randomUUID}from 'node:crypto';import {requireRule}from './authority.mjs';
export function scanAmounts(job){const amounts={};for(const scan of job.scans)if(['VALID','VALID_EXTRA'].includes(scan.outcome))amounts[scan.sku]=(amounts[scan.sku]||0)+scan.size;return amounts;}
export function classifyScan(s,serial){const pack=s.registry[serial],j=s.job;if(!pack)return 'INVALID';if(pack.consumedBy&&pack.consumedBy!==j.id)return 'USED_ELSEWHERE';if(pack.consumedBy===j.id)return 'DUPLICATE_SAME_JOB';const line=j.approved.bom.find(b=>b.sku===pack.sku&&b.unit===pack.unit);if(!line)return 'WRONG_SKU';return (scanAmounts(j)[pack.sku]||0)>=line.required?'VALID_EXTRA':'VALID';}
export function recordScan(s,p){requireRule(['IN_PROGRESS','REVIEW'].includes(s.job?.status),'SCAN_STATE','Product scans require a started job');requireRule(typeof p.serial==='string'&&p.serial.length<=160,'SERIAL_REQUIRED','Enter a registered sample pack code');const location=p.location;requireRule(location&&Number.isFinite(location.lat)&&Number.isFinite(location.lng)&&Number.isFinite(location.accuracy)&&location.accuracy>0&&['live','sample'].includes(location.mode),'SCAN_LOCATION','Record location and accuracy');if(s.job.status==='REVIEW')s.job.status='IN_PROGRESS';const pack=s.registry[p.serial];requireRule(!pack?.reservedFor||pack.reservedFor===s.job.id,'PACK_RESERVED','This pack is reserved for another job');const outcome=p.provisional?'PROVISIONAL':classifyScan(s,p.serial);const scan={id:randomUUID(),serial:p.serial,sku:pack?.sku||null,size:pack?.size||0,unit:pack?.unit||null,batch:pack?.batch||null,outcome,at:s.clock.now,receivedAt:Date.now(),location,validation:'Synthetic registry lookup; not signed packaging authentication',history:[]};if(['VALID','VALID_EXTRA'].includes(outcome)){pack.consumedBy=s.job.id;delete pack.reservedFor;}if(['INVALID','USED_ELSEWHERE','WRONG_SKU'].includes(outcome))scan.issue={status:'OPEN',reason:outcome};s.job.scans.push(scan);holdPack(s,scan);return scan;}
export const scanHandlers={
 SCAN_PACK(s,p,a){requireRule(a==='applicator','ACTOR_BLOCK','Applicator scans products');recordScan(s,p);},
 SCAN_KIT(s,p,a){requireRule(a==='presenter','ACTOR_BLOCK','Sample kit scanning is a presenter action');for(const line of s.job.approved.bom){for(const mix of line.packs){const recorded=s.job.scans.filter(r=>r.sku===line.sku&&r.size===mix.size&&['VALID','VALID_EXTRA'].includes(r.outcome)).length;for(let i=0;i<Math.max(0,mix.count-recorded);i++){if((scanAmounts(s.job)[line.sku]||0)>=line.required)break;const pack=Object.values(s.registry).find(r=>r.sku===line.sku&&r.size===mix.size&&!r.consumedBy&&(!r.reservedFor||r.reservedFor===s.job.id));requireRule(pack,'SAMPLE_STOCK','No free sample stock; reset the intended demo session');recordScan(s,{serial:pack.serial,location:{...s.job.site,accuracy:12,mode:'sample'}});}}}},
 RECONCILE_SCAN(s,p,a){requireRule(a==='applicator','ACTOR_BLOCK','Applicator reconciles their pending scan');const scan=s.job.scans.find(r=>r.id===p.scanId);requireRule(scan?.outcome==='PROVISIONAL','SCAN_PENDING','No provisional scan found');requireRule(!s.registry[scan.serial]?.reservedFor||s.registry[scan.serial].reservedFor===s.job.id,'PACK_RESERVED','This pack is reserved for another job');scan.history.push({outcome:'PROVISIONAL',at:scan.at});scan.outcome=classifyScan(s,scan.serial);scan.reconciledAt=s.clock.now;holdPack(s,scan);if(['VALID','VALID_EXTRA'].includes(scan.outcome))s.registry[scan.serial].consumedBy=s.job.id;else if(scan.outcome!=='DUPLICATE_SAME_JOB')scan.issue={status:'OPEN',reason:scan.outcome};},
 RESOLVE_SCAN(s,p,a){requireRule(a==='admin','ACTOR_BLOCK','Supervisor resolves rejected pack evidence');const scan=s.job.scans.find(r=>r.id===p.scanId);requireRule(scan?.issue?.status==='OPEN','SCAN_ISSUE','No open scan issue');requireRule(p.action==='removed-and-replaced'&&String(p.reason||'').trim().length>=15,'ISSUE_REASON','Document pack removal and replacement with a detailed reason');const replacement=s.job.scans.find(r=>r.serial===p.replacementSerial&&['VALID','VALID_EXTRA'].includes(r.outcome));requireRule(!scan.issue.expectedSku||replacement?.sku===scan.issue.expectedSku,'REPLACEMENT_SKU','Replacement must match the requested system SKU');requireRule(!scan.issue.request||scan.issue.request.serial===replacement?.serial,'REPLACEMENT_HANDOFF','Scan the exact pack supplied by the dealer');requireRule(replacement&&(!scan.sku||replacement.sku===scan.sku||scan.outcome==='WRONG_SKU'),'REPLACEMENT_REQUIRED','A valid relevant replacement must be recorded; an override cannot make a reused pack genuine');scan.issue={...scan.issue,status:'RESOLVED',reason:p.reason,replacementSerial:replacement.serial,reviewedAt:s.clock.now,reviewer:'Demo supervisor'};}
};


