import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {randomUUID}from 'node:crypto';import {initialState,applyCommand,verifyState}from '../src/domain/authority.mjs';import {handlers}from '../server/handlers.mjs';import {fixtures}from '../src/data/fixtures.mjs';import {nextStage,evaluateGate}from '../src/domain/execution.mjs';import {scanAmounts}from '../src/domain/scans.mjs';
const catalog=JSON.parse(fs.readFileSync(new URL('../config/catalog.json',import.meta.url)));
const run=(s,type,payload={},actor='presenter')=>applyCommand(s,{id:randomUUID(),sessionId:s.id,expectedRevision:s.revision,type,payload,actor},handlers).state;
function booked(){let s=run(initialState('story-test',catalog),'START_STORY');for(const value of ['YES','HAIRLINE','Tomorrow · 10 am–12 pm','CONFIRM'])s=run(s,'ENQUIRY_REPLY',{value},'homeowner');return s;}
function started(){let s=booked();s=run(s,'ACCEPT_LEAD',{},'applicator');s=run(s,'CHECK_IN',{location:{...s.job.site,accuracy:12,mode:'sample'}},'applicator');s=run(s,'SAVE_DIAGNOSIS',{answers:fixtures.terrace.answers,measurement:fixtures.terrace.measurement,photos:s.catalog.diagnosis_photos.TERRACE.map(view=>({view,mode:'sample'}))},'applicator');s=run(s,'CALCULATE_PLAN',{},'applicator');s=run(s,'SEND_QUOTE',{},'applicator');const q=s.job.quotes.at(-1);assert.ok(q.options.length<=2);s=run(s,'APPROVE_QUOTE',{quoteId:q.id,token:q.token,packageCode:'TERRACE_SHIELD_PLUS'},'homeowner');s=run(s,'TAG_DEALER',{dealerId:'dealer-001'},'applicator');s=run(s,'READY_KIT',{},'dealer');s=run(s,'VERIFY_START',{jobId:s.job.id,purpose:'START',code:s.job.otps.START.code},'applicator');return s;}
test('a homeowner concern pauses handover and reserves no approval by silence',()=>{let s=started();s.job.status='HANDOVER';s.job.otps.CLOSE={verified:true,code:'123456'};s=run(s,'REQUEST_SUPPORT',{reason:'The drain junction still needs inspection'},'homeowner');assert.equal(s.job.handoverHold,true);assert.equal(s.job.otps.CLOSE,null);assert.equal(s.job.status,'REVIEW');assert.equal(evaluateGate(s,false)[5].pass,false);s=run(s,'RESOLVE_SUPPORT',{reason:'Reviewed the drain junction concern and documented correction with the customer'},'admin');assert.equal(s.job.handoverHold,false);assert.equal(s.job.otps.CLOSE,null);assert.equal(evaluateGate(s,true)[5].pass,false);});
test('a replacement reservation prevents a different job from consuming that pack',()=>{let s=started();s.registry['DEMO-WPM810-20-001'].reservedFor='another-job';assert.throws(()=>run(s,'SCAN_PACK',{serial:'DEMO-WPM810-20-001',location:{...s.job.site,accuracy:12,mode:'sample'}},'applicator'),/reserved for another/);assert.deepEqual(scanAmounts(s.job),{});});
test('website context, consent and booking survive acceptance and are tamper checked',()=>{let s=booked();assert.equal(s.presentation.serviceConsent,true);assert.equal(s.job,null);s=run(s,'ACCEPT_LEAD',{},'applicator');assert.equal(s.customer.name,'Ananya Rao');assert.equal(s.customer.address,'Indiranagar, Bengaluru');assert.equal(s.lead.slot,s.presentation.slot);assert.ok(s.messages.some(m=>m.kind==='website'));assert.ok(verifyState(s));s.presentation.context.city='Changed';assert.equal(verifyState(s),false);});
test('consent refusal, resume and structural concerns cannot silently book a visit',()=>{let s=run(initialState('story-stop',catalog),'START_STORY');s=run(s,'ENQUIRY_REPLY',{value:'NO'},'homeowner');assert.equal(s.lead,null);assert.throws(()=>run(s,'ENQUIRY_REPLY',{value:'YES'},'homeowner'),/stopped/);s=run(s,'RESUME_MESSAGES',{},'homeowner');s=run(s,'ENQUIRY_REPLY',{value:'YES'},'homeowner');s=run(s,'ENQUIRY_REPLY',{value:'STRUCTURAL'},'homeowner');assert.equal(s.presentation.step,'BLOCKED');assert.equal(s.lead,null);assert.throws(()=>run(s,'ENQUIRY_REPLY',{value:'CONFIRM'},'homeowner'),/awaiting/);});
test('wrong SKU has no quantity credit and needs exact dealer-supplied replacement review',()=>{let s=started();s=run(s,'INJECT_WRONG_SKU');const bad=s.job.scans.at(-1);assert.deepEqual(scanAmounts(s.job),{});assert.equal(evaluateGate(s,false)[0].pass,false);s=run(s,'REQUEST_REPLACEMENT',{scanId:bad.id,sku:'WPM810',size:20},'applicator');assert.throws(()=>run(s,'SUPPLY_REPLACEMENT',{scanId:bad.id,serial:'DEMO-WPM004-20-001'},'dealer'),/matching/);s=run(s,'SUPPLY_REPLACEMENT',{scanId:bad.id,serial:'DEMO-WPM810-20-001'},'dealer');assert.equal(s.registry['DEMO-WPM810-20-001'].reservedFor,s.job.id);assert.throws(()=>run(s,'RESOLVE_SCAN',{scanId:bad.id,replacementSerial:'DEMO-WPM810-20-001',action:'removed-and-replaced',reason:'Rejected pack removed and correct product checked'},'admin'),/replacement/i);s=run(s,'SCAN_PACK',{serial:'DEMO-WPM810-20-002',location:{...s.job.site,accuracy:12,mode:'sample'}},'applicator');assert.throws(()=>run(s,'RESOLVE_SCAN',{scanId:bad.id,replacementSerial:'DEMO-WPM810-20-002',action:'removed-and-replaced',reason:'Rejected pack removed and correct product checked'},'admin'),/exact pack/);s=run(s,'SCAN_PACK',{serial:'DEMO-WPM810-20-001',location:{...s.job.site,accuracy:12,mode:'sample'}},'applicator');s=run(s,'RESOLVE_SCAN',{scanId:bad.id,replacementSerial:'DEMO-WPM810-20-001',action:'removed-and-replaced',reason:'Rejected pack removed and supplied replacement physically checked'},'admin');assert.equal(s.job.scans[0].outcome,'WRONG_SKU');assert.equal(s.job.scans[0].issue.status,'RESOLVED');assert.ok(verifyState(s));});
test('dealer shortage blocks readiness and invoice declaration needs separate reconciliation',()=>{let s=started();s.job.status='APPROVED';s.job.kit.status='REQUESTED';s=run(s,'DEALER_SHORTAGE',{reason:'Primer size unavailable in store'},'dealer');assert.throws(()=>run(s,'READY_KIT',{},'dealer'),/shortage/);s=run(s,'RESOLVE_SHORTAGE',{reason:'Approved product stock restored with exact requested packs'},'admin');s=run(s,'ADVANCE',{minutes:2});s=run(s,'READY_KIT',{},'dealer');s=run(s,'RECORD_INVOICE',{number:'INV-123',amountPaise:5014000},'dealer');assert.equal(s.job.kit.invoice.status,'DECLARED');assert.throws(()=>run(s,'RECONCILE_INVOICE',{reason:'ok'},'admin'),/evidence/);s=run(s,'RECONCILE_INVOICE',{reason:'Matched recorded invoice against approved material lines'},'admin');assert.equal(s.job.kit.invoice.status,'RECONCILED');});
test('full story issuance remains digest-valid and issued evidence cannot be rewritten',()=>{let s=started();s=run(s,'SCAN_KIT');while(nextStage(s)){const t=nextStage(s);s=run(s,'NEXT_CURE');if(t.challenge_code)s=run(s,'REQUEST_CHALLENGE',{stageKey:t.key},'applicator');s=run(s,'CAPTURE_STAGE',{stageKey:t.key,mode:'sample',location:{...s.job.site,accuracy:12,mode:'sample'},challengeCode:s.job.challenge?.code,weatherAcknowledged:true},'applicator');s=run(s,'ASSESS_CAPTURE',{captureId:s.job.captures.at(-1).id,status:'PASS',reason:'Reference record reviewed against required stage and code',challengeConfirmed:true,floodResult:'PASS'},'admin');}s=run(s,'EVALUATE_GATE',{},'admin');s=run(s,'REQUEST_CLOSE',{},'applicator');s=run(s,'VERIFY_CLOSE',{purpose:'CLOSE',jobId:s.job.id,code:s.job.otps.CLOSE.code},'applicator');s=run(s,'EVALUATE_GATE',{},'admin');s=run(s,'ISSUE_PASSPORT',{},'admin');assert.ok(verifyState(s));assert.throws(()=>run(s,'ASSESS_CAPTURE',{captureId:s.job.captures[0].id,status:'FAIL',reason:'Attempt to overwrite an already issued reviewed record'},'admin'),/cannot be rewritten/);s=run(s,'ACK_PAYMENT',{status:'PAID'},'homeowner');assert.equal(s.payments.length,0);s=run(s,'CONFIRM_RECEIPT',{},'applicator');assert.equal(s.payments[0].status,'ACKNOWLEDGED');assert.throws(()=>run(s,'ACK_PAYMENT',{status:'PENDING'},'homeowner'),/cannot be overwritten/);s=run(s,'RATE_JOB',{rating:2,comment:'Needs follow-up'},'homeowner');assert.equal(s.job.support.status,'OPEN');s=run(s,'CARE_CHOICE',{enabled:false},'homeowner');assert.equal(s.customer.marketingConsent,false);assert.ok(verifyState(s));});



