import {useEffect,useState}from 'react';
import {useWorkspace}from '../adapters/useWorkspace';
import {Field,Notice}from './components';
import {price}from './Plan';

type Row=any;
const terminal=['COMPLETED','CANCELLED'];
export function applicatorGroups(work:Row[]){
 const groups=new Map<string,Row[]>();
 for(const row of work){if(!row.profile?.id)continue;const rows=groups.get(row.profile.id)||[];rows.push(row);groups.set(row.profile.id,rows);}
 return [...groups.entries()].map(([id,rows])=>({id,rows,profile:(rows.find(r=>r.job)||rows[0]).profile}));
}
function uniqueJobs(rows:Row[]){return [...new Map(rows.filter(r=>r.job).map(r=>[r.job.id,r])).values()];}
function needsReview(r:Row){return r.job.status==='REVIEW'||r.job.scans.some((s:any)=>s.issue?.status==='OPEN')||r.job.captures.some((c:any)=>!c.superseded&&(!c.assessment||c.assessment.status==='FAIL'));}
export function ApplicatorDirectory({work,onManage}:{work:Row[];onManage:(id:string)=>void}){
 const [query,setQuery]=useState('');
 const groups=applicatorGroups(work).filter(g=>(g.profile.name+' '+g.id+' '+g.profile.city).toLowerCase().includes(query.toLowerCase()));
 return <article className="admin-slab applicator-directory"><div className="panel-title"><div><h3>Your applicator network</h3><p>Certification, performance and assigned work in one place.</p></div><span className="pill">{groups.length} {groups.length===1?'APPLICATOR':'APPLICATORS'}</span></div><div className="table-toolbar"><input aria-label="Search applicators" placeholder="Search by name, member ID or city…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="table-scroll"><table><thead><tr><th>Applicator</th><th>Coverage</th><th>Tier</th><th>Assigned work</th><th>Attention</th><th/></tr></thead><tbody>{groups.map(g=>{const jobs=uniqueJobs(g.rows);return <tr key={g.id}><td><div className="member-name"><span className="member-avatar">{g.profile.name.split(' ').map((n:string)=>n[0]).slice(0,2).join('')}</span><div><b>{g.profile.name}</b><small>{g.id}</small></div></div></td><td>{g.profile.city==='BLR'?'Bengaluru':g.profile.city}<small>{g.profile.radiusKm} km service radius</small></td><td><span className="member-tier">{g.profile.tier}</span></td><td>{jobs.length} jobs<small>{jobs.filter(r=>!terminal.includes(r.job.status)).length} active · {jobs.filter(r=>r.job.status==='COMPLETED').length} completed</small></td><td>{jobs.filter(needsReview).length} reviews</td><td><button className="member-manage" onClick={()=>onManage(g.id)}>Manage →</button></td></tr>})}</tbody></table></div>{!groups.length&&<div className="member-empty">No applicators match your search.</div>}</article>;
}
export function ApplicatorProfile({id,work,onBack,onJob,onSaved}:{id:string;work:Row[];onBack:()=>void;onJob:(id:string)=>void;onSaved:()=>void}){
 const rows=work.filter(r=>r.profile?.id===id),jobs=uniqueJobs(rows),first=jobs[0]||rows[0];
 const [tab,setTab]=useState('Overview'),[context,setContext]=useState(first?.id||''),[filter,setFilter]=useState('ALL');
 const current=rows.find(r=>r.id===context)||first;
 const {state:s,error,busy,command}=useWorkspace(current?.id||'');
 const [status,setStatus]=useState('CERTIFIED'),[reason,setReason]=useState(''),[saved,setSaved]=useState('');
 useEffect(()=>{if(s?.profile)setStatus(s.profile.status)},[s?.id,s?.profile.status]);
 useEffect(()=>{setReason('');setSaved('')},[current?.id]);
 if(!first)return <article className="admin-slab"><Notice title="Applicator not found">This member is no longer available in the current records.</Notice><button onClick={onBack}>← All applicators</button></article>;
 const profile=(s?.id===current.id?s.profile:null)||current.profile,completed=jobs.filter(r=>r.job.status==='COMPLETED'),active=jobs.filter(r=>!terminal.includes(r.job.status)),review=jobs.filter(needsReview);
 const ratings=jobs.filter(r=>r.job.rating),average=ratings.length?ratings.reduce((n,r)=>n+r.job.rating.value,0)/ratings.length:null;
 const payments=jobs.flatMap(r=>r.payments||[]),reported=payments.reduce((n,p)=>n+p.amountPaise,0),points=jobs.flatMap(r=>r.points||[]),available=points.reduce((n,p)=>n+(p.availableDelta??(['RELEASED','REVERSED'].includes(p.status)?p.amount:0)),0),held=points.reduce((n,p)=>n+(p.heldDelta||0),0);
 const visible=jobs.filter(r=>filter==='ALL'||(filter==='ACTIVE'?!terminal.includes(r.job.status):filter==='REVIEW'?needsReview(r):r.job.status===filter));
 async function save(){setSaved('');if(await command('SET_CERTIFICATION',{status,reason:reason.trim()},'admin')){setSaved('Certification decision saved to '+(current.job?.code||'this record')+'.');onSaved();}}
 const contextField=<Field label="Certification record"><select value={current.id} disabled={busy} onChange={e=>{setContext(e.target.value);setSaved('');setReason('')}}>{rows.map(r=><option key={r.id} value={r.id}>{r.job?.code||'Onboarding record'} · {r.profile.status}{r.job?' · '+r.job.status.replaceAll('_',' '):''}</option>)}</select></Field>;
 return <div className="applicator-profile"><button className="member-back" onClick={onBack}>← All applicators</button><section className="member-hero"><div className="member-hero-main"><span className="member-avatar large">{profile.name.split(' ').map((n:string)=>n[0]).slice(0,2).join('')}</span><div><span className="eyebrow">APPLICATOR PROFILE · {id}</span><h2>{profile.name}</h2><p>{profile.city==='BLR'?'Bengaluru':profile.city} · {profile.radiusKm} km service radius</p><div className="member-badges"><span className="member-tier">{profile.tier} MEMBER</span><span className={'status-badge '+profile.status}>{profile.status}</span><small>Selected record: {current.job?.code||'Onboarding'}</small></div></div></div><button className="primary" onClick={()=>setTab('Certification')}>Review certification</button></section><div className="member-metrics">{[['Assigned jobs',jobs.length,'All recorded work'],['Active jobs',active.length,completed.length+' completed'],['Homeowner rating',average===null?'—':average.toFixed(1)+' / 5',ratings.length?ratings.length+' recorded ratings':'No ratings recorded'],['Needs review',review.length,'Product or evidence exceptions']].map(([label,value,note])=><article key={label}><small>{label}</small><b>{value}</b><span>{note}</span></article>)}</div><nav className="member-tabs" aria-label="Applicator profile tabs">{['Overview','Jobs','Certification','Activity'].map(t=><button key={t} aria-current={tab===t?'page':undefined} className={tab===t?'selected':''} onClick={()=>setTab(t)}>{t}{t==='Jobs'&&<span>{jobs.length}</span>}</button>)}</nav>{error&&<Notice tone="blocked" title={error}/>} {saved&&<Notice tone="success" title={saved}/>}
 {tab==='Overview'&&<div className="member-grid"><article className="admin-slab"><span className="eyebrow">MEMBER DETAILS</span><h3>Identity & coverage</h3><dl className="member-facts"><div><dt>Member ID</dt><dd>{id}</dd></div><div><dt>Service city</dt><dd>{profile.city==='BLR'?'Bengaluru':profile.city}</dd></div><div><dt>Coverage radius</dt><dd>{profile.radiusKm} km</dd></div><div><dt>Account role</dt><dd>Applicator</dd></div><div><dt>KYC documents</dt><dd>No documents on file</dd></div><div><dt>Training records</dt><dd>No training records on file</dd></div></dl></article><article className="admin-slab"><span className="eyebrow">PERFORMANCE</span><h3>Quality & membership</h3><div className="member-score"><b>{profile.score}<small>/100</small></b><span>{profile.tier} tier</span></div><progress max={100} value={profile.score}/><p className="body-copy">{profile.scoreReason}</p><p className="member-caption">Quality and tier belong to the selected record; they are not recalculated from the network totals.</p></article><article className="admin-slab"><span className="eyebrow">COMMERCIAL RECORD</span><h3>Earnings & points</h3><div className="member-money">{price(reported)}<small>Applicator-reported payments</small></div><dl className="member-facts"><div><dt>Available points</dt><dd>{available}</dd></div><div><dt>Points on hold</dt><dd>{held}</dd></div><div><dt>Provider-verified payouts</dt><dd>Not connected</dd></div></dl><p className="member-caption">Reported receipts are not verified collections or a payout balance.</p></article><article className="admin-slab"><div className="panel-title"><div><span className="eyebrow">ACTION NEEDED</span><h3>Work requiring attention</h3></div><span className="pill">{review.length}</span></div>{review.length?review.slice(0,4).map(r=><button className="attention-row" key={r.id} onClick={()=>onJob(r.id)}><span><b>{r.job.code}</b><small>{r.customer?.name} · {r.job.areaType==='TERRACE'?'Terrace':'Bathroom'}</small></span><span>Review job →</span></button>):<div className="member-empty">No open product or evidence reviews.</div>}<button className="secondary" onClick={()=>setTab('Jobs')}>View all assigned jobs</button></article></div>}
 {tab==='Jobs'&&<article className="admin-slab"><div className="panel-title"><h3>Assigned work</h3><select aria-label="Filter applicator jobs" value={filter} onChange={e=>setFilter(e.target.value)}>{['ALL','ACTIVE','REVIEW','COMPLETED','CANCELLED'].map(t=><option key={t} value={t}>{t==='ALL'?'All jobs':t.charAt(0)+t.slice(1).toLowerCase()}</option>)}</select></div><div className="table-scroll"><table><thead><tr><th>Job / homeowner</th><th>Source</th><th>Status</th><th>Approved value</th><th>Rating</th><th/></tr></thead><tbody>{visible.map(r=><tr key={r.id}><td><b>{r.job.code}</b><small>{r.customer?.name}</small></td><td>{r.job.mode==='ardex'?'Ardex lead':'Own customer'}</td><td><span className={'status-badge '+r.job.status}>{r.job.status.replaceAll('_',' ')}</span></td><td>{r.job.approved?price(r.job.approved.totalPaise):'Awaiting quote'}</td><td>{r.job.rating?r.job.rating.value+' / 5':'—'}</td><td><button onClick={()=>onJob(r.id)}>Open job →</button></td></tr>)}</tbody></table></div>{!visible.length&&<div className="member-empty">No jobs in this view.</div>}</article>}
 {tab==='Certification'&&<div className="member-grid certification-grid"><article className="admin-slab"><span className="eyebrow">MEMBERSHIP REVIEW</span><h3>Certification decision</h3><p className="body-copy">Select the record to review. This decision changes eligibility on that record and is added to its event history.</p>{contextField}<Field label="Certification status"><select value={status} disabled={busy||!s||s.id!==current.id} onChange={e=>setStatus(e.target.value)}><option value="PENDING">Pending review</option><option value="VERIFIED">Verified</option><option value="CERTIFIED">Certified</option><option value="SUSPENDED">Suspended</option></select></Field><Field label="Decision reason"><textarea value={reason} disabled={busy} onChange={e=>setReason(e.target.value)} placeholder="Record the evidence and reason for this decision…"/></Field>{status==='SUSPENDED'&&<Notice tone="blocked" title="Lead eligibility will pause">This record cannot accept a new Ardex lead while suspended. Existing work and evidence are retained.</Notice>}<button className="primary" disabled={busy||!s||s.id!==current.id||reason.trim().length<15} onClick={save}>{busy?'Saving decision…':'Save certification decision'}</button><p className="member-caption">A reason of at least 15 characters is required. Admin and Super Admin have permission to record this decision.</p></article><article className="admin-slab"><span className="eyebrow">CURRENT RECORD</span><h3>{current.job?.code||'Onboarding'}</h3><dl className="member-facts"><div><dt>Certification</dt><dd>{profile.status}</dd></div><div><dt>Onboarding</dt><dd>{profile.loggedIn?'Completed':'Not completed'}</dd></div><div><dt>Lead eligibility</dt><dd>{profile.loggedIn&&profile.status==='CERTIFIED'&&profile.city==='BLR'&&profile.radiusKm>0?'Eligible':'Not eligible'}</dd></div></dl><h4>Latest decision reason</h4><p className="body-copy">{profile.reviewReason||'No supervisor decision has been recorded.'}</p><Notice title="Record scope">The current data model stores certification in each workspace. A decision here does not suspend every job or disable the applicator’s sign-in account.</Notice></article></div>}
 {tab==='Activity'&&<article className="admin-slab"><span className="eyebrow">MEMBER HISTORY</span><h3>Profile & certification activity</h3>{contextField}<div className="member-activity">{s?.events.filter((e:any)=>['SET_CERTIFICATION','SAVE_PROFILE','VERIFY_LOGIN','LOGOUT'].includes(e.type)).slice().reverse().map((e:any)=><div key={e.id}><span className="activity-dot"/><div><b>{({SET_CERTIFICATION:'Certification decision saved',SAVE_PROFILE:'Profile updated',VERIFY_LOGIN:'Onboarding completed',LOGOUT:'Applicator signed out'} as Record<string,string>)[e.type]}</b><small>{e.actor} · {new Date(e.receivedAt).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})}</small><code>Record #{e.sequence}</code></div></div>)}</div>{s&&!s.events.some((e:any)=>['SET_CERTIFICATION','SAVE_PROFILE','VERIFY_LOGIN','LOGOUT'].includes(e.type))&&<div className="member-empty">No profile or certification events recorded yet.</div>}<p className="member-caption">Job execution history is available from each assigned job. All decisions are checked by the same local authority.</p></article>}
 </div>;
}
