import {adminUrl} from '../adapters/service-url.mjs';
import {useEffect,useRef,useState}from 'react';import {Phone}from './Phone';import {LiveConversation,OutcomeView}from './JourneyViews';import {DealerView}from './DealerView';import {CorrectionFlow}from './CorrectionFlow';import {Intake}from './Intake';import {DiagnosisView}from './Diagnosis';import {PlanView}from './Plan';import {QuoteView,KitView}from './Commercial';import {ProofView,ReviewProof}from './Proof';import type {WorkflowProps}from './Workflow';
const chapters=[
{id:'enquiry',name:'Enquiry',title:'A clearer next step.',question:'Can an enquiry become a useful visit?',copy:'The website details travel with Ananya. Sakhaa confirms what is missing and prepares the visit.',authority:'AI assistance · customer confirms the facts'},
{id:'inspection',name:'Inspection',title:'The site decides the system.',question:'Does the recommendation follow the condition?',copy:'Ravi confirms the condition, checks in and measures. Approved rules turn those inputs into eligible systems and quantities.',authority:'Human diagnosis · approved calculation rules'},
{id:'decision',name:'Decision',title:'An agreed scope. A clear price.',question:'Does Ananya understand what she is accepting?',copy:'Compare the eligible options, inspect the scope and approve one quote. Extra work requires a new agreement.',authority:'Customer decision · frozen quote version'},
{id:'supply',name:'Supply',title:'The specification reaches the supplier.',question:'Will the kit match the approved system?',copy:'The tagged dealer receives exact products, quantities and pack sizes. Readiness is a declaration; scans check the supplied packs.',authority:'Dealer declaration · approved material list'},
{id:'exception',name:'Exception',title:'The mistake stays visible. So does the correction.',question:'What happens when someone makes a mistake?',copy:'A wrong SKU is rejected. Ravi requests the right product, the dealer supplies it, and the supervisor reviews the on-site replacement.',authority:'Registry rules detect · people correct and review'},
{id:'completion',name:'Completion',title:'A handover with evidence behind it.',question:'What supports the completion record?',copy:'Recorded stages, required curing, a paired flood test and homeowner confirmations support the review. Missing checks block issuance.',authority:'Approved checks · human evidence assessment'},
{id:'outcome',name:'Outcome',title:'The job ends. The record remains.',question:'Can ARDEX trace the commercial result?',copy:'One record connects the customer, agreed scope, dealer, product scans, work and payment acknowledgements.',authority:'Traceable values · no inferred profit or sales lift'}];
export function GuidedPresentation({s,command,busy,refresh,user}:{refresh:(reset?:boolean)=>Promise<any>;user:any}&WorkflowProps){const [chapter,setChapter]=useState(()=>{try{return Number(sessionStorage.getItem('chapter:'+s.id)||0)}catch{return 0}}),[advancing,setAdvancing]=useState(false),[error,setError]=useState('');const autoBegin=useRef(false);useEffect(()=>{if(!autoBegin.current&&user.role==='presenter'&&!s.presentation&&!s.job&&!s.lead&&new URLSearchParams(location.search).get('begin')==='1'){autoBegin.current=true;command('START_STORY',{},'presenter')}},[s.id,s.presentation,user.role]);const presenter=user.role==='presenter',appAllowed=['presenter','applicator'].includes(user.role),homeAllowed=['presenter','homeowner'].includes(user.role),dealerAllowed=['presenter','dealer'].includes(user.role);const c=chapters[chapter]||chapters[0],j=s.job;useEffect(()=>{sessionStorage.setItem('chapter:'+s.id,String(chapter))},[chapter,s.id]);function fresh(){location.href='/?session='+crypto.randomUUID()+'&focus=story&begin=1';}
const available=[true,!!s.lead||!!j,!!j?.plan,!!j?.approved,j&&['IN_PROGRESS','REVIEW','HANDOVER','COMPLETED'].includes(j.status),j&&['IN_PROGRESS','REVIEW','HANDOVER','COMPLETED'].includes(j.status)&&!j.scans.some((x:any)=>x.issue?.status==='OPEN'),j?.status==='COMPLETED'];
async function nextRecord(){setAdvancing(true);setError('');try{let current=await refresh();const stage=current.job.approved.stages.find((t:any)=>current.job.captures.filter((p:any)=>!p.superseded&&p.stageKey===t.key).length<t.shots);if(!stage)return;if(!await command('NEXT_CURE',{},'presenter'))return;if(stage.challenge_code&&!await command('REQUEST_CHALLENGE',{stageKey:stage.key},'applicator'))return;current=await refresh();await command('CAPTURE_STAGE',{stageKey:stage.key,mode:'sample',location:{...current.job.site,accuracy:12,mode:'sample'},challengeCode:current.job.challenge?.code,weatherAcknowledged:true},'applicator');}catch(e){setError(String(e))}finally{setAdvancing(false)}}
const phone=(title:string,kind:string,body:any)=><section className="phone-column"><div className="panel-title"><strong>{title}</strong><span>{j?.code||'Website enquiry'}</span></div><Phone kind={kind}>{body}</Phone></section>;
const app=(body:any)=>phone('Ravi · Applicator','app-device',<><div className="work-phone-header"><img src="/brand/ardex-endura.png" alt="ARDEX ENDURA"/><b>PRO</b><span className="app-avatar">RK</span></div><div className="phone-scroll">{body}</div><div className="guided-phone-label">ARDEX PRO · Your work, recorded</div></>);
const home=()=>phone('Ananya · Homeowner','wa-device',<LiveConversation s={s} command={command} busy={busy} allowed={homeAllowed}/>);
const dealer=()=>phone('Akshaya · Dealer','wa-device',<DealerView s={s} command={command} busy={busy} allowed={dealerAllowed}/>);
return <section className="guided-presentation"><div className="presentation-topline"><span>ANANYA’S TERRACE · BENGALURU</span><div><a href={adminUrl('/admin.html?session=')+s.id} target="_blank" rel="noreferrer">Inspect this record ↗</a>{presenter&&<button onClick={fresh}>Start a fresh journey</button>}</div></div><nav className="chapter-nav" aria-label="Presentation chapters">{chapters.map((x,i)=><button key={x.id} aria-current={chapter===i?'step':undefined} disabled={!available[i]} onClick={()=>setChapter(i)}><span>{String(i+1).padStart(2,'0')}</span>{x.name}</button>)}</nav><div className="chapter-heading"><div><span className="eyebrow">{c.name.toUpperCase()}</span><h1>{c.title}</h1></div><p>{c.copy}</p></div><div className="chapter-authority"><i>●</i>{c.authority}</div>{error&&<p role="alert">{error}</p>}
{!s.presentation?<div className="presentation-welcome"><img src="/site-photos/terrace-before.png" onError={e=>{e.currentTarget.src='/site-photos/terrace-before.jpg'}} alt="Terrace reference"/><div><h2>One homeowner. One connected job.</h2><p>Ananya has a leaking terrace. Follow her enquiry through a measured scope, material supply, a product mistake and an accountable handover.</p><p>Existing jobs are preserved. This starts a separate fictional customer record.</p>{presenter?<button className="primary" disabled={busy} onClick={()=>{if(s.job||s.lead)fresh();else command('START_STORY',{},'presenter')}}>Begin Ananya’s journey</button>:<p>Ask the presenter to start the shared journey. Your role can explore its assigned actions.</p>}</div></div>:<>
<div className={'chapter-stage '+(chapter===4?'chapter-three':chapter===5?'chapter-two':chapter===6?'chapter-outcome':'chapter-one')}>
{chapter===0&&home()}
{chapter===1&&app(<><h2>Confirm the site.</h2>{!j?<Intake s={s} command={command} busy={busy||!appAllowed}/>:<>{['VISIT_BOOKED','DIAGNOSIS'].includes(j.status)&&<DiagnosisView key={"diagnosis-"+j.id} s={s} command={command} busy={busy||!appAllowed}/>}<PlanView key={"plan-"+(j.diagnosis?.id||j.id)} s={s} command={command} busy={busy||!appAllowed}/><QuoteView s={s} command={command} busy={busy||!appAllowed}/></>}</>)}
{chapter===2&&home()}
{chapter===3&&<>{!j.kit?app(<KitView s={s} command={command} busy={busy||!appAllowed}/>):dealer()}</>}
{chapter===4&&<>{app(<><KitView s={s} command={command} busy={busy||!appAllowed}/>{presenter&&!j.scans.some((x:any)=>x.outcome==='WRONG_SKU')&&<div className="exception-intro"><h2>One wrong pack.</h2><p>A genuine registered product can still be the wrong product for this scope.</p><button className="primary" disabled={busy} onClick={()=>command('INJECT_WRONG_SKU',{},'presenter')}>Scan the wrong product</button></div>}<CorrectionFlow s={s} command={command} busy={busy} owner="applicator" allowed={appAllowed}/></>)}{dealer()}<article className="human-review-card"><span className="eyebrow">ARDEX · HUMAN REVIEW</span><h2>Verify the correction.</h2><p>The rejected scan remains. An eligible replacement must be supplied and scanned before clearance.</p><CorrectionFlow s={s} command={command} busy={busy} owner="admin" allowed={presenter}/><a href={adminUrl('/admin.html?session=')+s.id} target="_blank" rel="noreferrer">Open admin evidence ↗</a></article></>}
{chapter===5&&<>{app(<><KitView s={s} command={command} busy={busy||!appAllowed}/><ProofView s={s} command={command} busy={busy||!appAllowed} onReview={presenter?()=>{const review=document.getElementById('proof-assessment');review?.scrollIntoView({behavior:'smooth',block:'start'});review?.querySelector('textarea')?.focus({preventScroll:true});}:undefined}/></>)}<article className="human-review-card"><span className="eyebrow">REQUIRED EVIDENCE · REVIEWED BY A PERSON</span><h2>Record. Inspect. Confirm.</h2>{presenter&&['IN_PROGRESS','REVIEW'].includes(j.status)&&<div className="presentation-tools"><h3>1. Record the stage photos</h3><p>{j.captures.filter((x:any)=>!x.superseded).length} of {j.approved.stages.reduce((n:number,t:any)=>n+t.shots,0)} required photos recorded. Click <b>Record next reference stage</b> once per missing photo. Running the checks does not create photos.</p><button disabled={busy||advancing} onClick={()=>command('SCAN_KIT',{},'presenter')}>Record the approved kit scans</button><button disabled={busy||advancing||j.scans.some((x:any)=>x.issue?.status==='OPEN')||j.approved.stages.every((t:any)=>j.captures.filter((x:any)=>!x.superseded&&x.stageKey===t.key).length>=t.shots)} onClick={nextRecord}>{j.approved.stages.every((t:any)=>j.captures.filter((x:any)=>!x.superseded&&x.stageKey===t.key).length>=t.shots)?'All stage photos recorded':'Record next reference stage'}</button><p>Once every shot is recorded, capture is complete. Continue with <a href="#proof-assessment">Proof assessment below</a>; recording does not approve photos.</p><small>Generated references; presentation clock advances to the required curing time. Field evidence needs actual camera capture.</small></div>}<h3>2. Review photos, then confirm handover</h3><p>After recording every shot, enter a decision reason, confirm the required visible codes and paired flood-test outcome, and pass each acceptable reference photo below. Then run the checks and request the closing code.</p><ReviewProof s={s} command={command} busy={busy||!presenter}/><details className="homeowner-handover"><summary>Homeowner confirmations & messages</summary><div className="handover-conversation"><LiveConversation s={s} command={command} busy={busy} allowed={homeAllowed}/></div></details></article></>}
{chapter===6&&<><OutcomeView s={s} command={command} busy={busy} allowed={appAllowed}/>{home()}</>}
</div><footer className="chapter-footer"><p>{c.question}</p><div><button disabled={chapter===0} onClick={()=>setChapter(n=>n-1)}>← Previous chapter</button><button className="primary" disabled={chapter===6||!available[chapter+1]} onClick={()=>setChapter(n=>n+1)}>{chapter===6?'Journey complete':'Continue to '+chapters[chapter+1]?.name+' →'}</button></div></footer>{chapter<6&&!available[chapter+1]&&<p className="chapter-next-hint">{['Confirm the enquiry and book the visit to continue.','Accept, inspect and calculate the plan to continue.','Approve the homeowner’s quote to continue.','Mark the kit ready and confirm work start to continue.','Complete the product correction before clearance.','Review the evidence, capture handover confirmation and issue the completion record.'][chapter]}</p>}
{chapter===3&&j.status==='KIT_READY'&&<div className="supply-start"><h3>Kit ready. Homeowner permission comes next.</h3><div className="supply-start-grid">{app(<KitView s={s} command={command} busy={busy||!appAllowed}/>)}{home()}</div></div>}</>}
</section>;
}


