import {adminUrl} from '../adapters/service-url.mjs';
import {GuidedPresentation}from './GuidedPresentation';import {LiveConversation}from './JourneyViews';
import {Phone}from './Phone';import {DealerView}from './DealerView';
import {sitePhoto}from './SitePhoto';
import {JobHistory}from './JobHistory';
import {CancelControls}from './CancelControls';
import {useEffect,useRef,useState}from 'react';import {useWorkspace}from '../adapters/useWorkspace';import {Action,Field,Notice}from './components';import {Intake}from './Intake';import {DiagnosisView}from './Diagnosis';import {PlanView,price}from './Plan';import {QuoteView,HomeownerQuote,KitView}from './Commercial';import {ProofView}from './Proof';import {exportDocument}from '../adapters/export-document';import type {DemoUser}from './Auth';
export type WorkflowProps={s:any;command:(type:string,payload?:any,actor?:string)=>Promise<boolean>;busy:boolean};
export function ProfileView({s,command,busy}:WorkflowProps){const [code,setCode]=useState('');return <><div className="greeting">YOUR WORK, VERIFIED</div><h2>Hello, {s.profile.name.split(' ')[0]}.</h2>{!s.profile.loggedIn?<><Notice title="Set up your applicator profile">Confirm your phone to activate your profile and job inbox.</Notice>{!s.login?<Action disabled={busy} onClick={()=>command('REQUEST_LOGIN')}>Send login code</Action>:<><Notice title="Your verification code">456123 · expires in 5 minutes</Notice><Field label="Login code"><input value={code} onChange={e=>setCode(e.target.value)} maxLength={6}/></Field><Action disabled={busy} onClick={()=>command('VERIFY_LOGIN',{code})}>Complete onboarding</Action></>}</>:<><div className="digital-id"><img src="/brand/ardex-endura.png" alt="ARDEX ENDURA"/><span>APPLICATOR ID</span><h3>{s.profile.name}</h3><b>{s.profile.status} · {s.profile.tier}</b><small>{s.profile.id} · Bengaluru</small></div><Notice tone={s.profile.status==='CERTIFIED'?'success':'blocked'} title={s.profile.status}>{s.profile.score}/100 · {s.profile.scoreReason}</Notice></>}</>}
export function Workflow({id,role,user}:{id:string;role:string;user:DemoUser}){
const {state:s,error,busy,command,refresh,pending,retryPending,discardPending}=useWorkspace(id),[tab,setTab]=useState('jobs'),[checkpoint,setCheckpoint]=useState('start'),[mode,setMode]=useState('terrace'),[checkpointBusy,setCheckpointBusy]=useState(false),[checkpointError,setCheckpointError]=useState('');
const appScroll=useRef<HTMLDivElement>(null),chatScroll=useRef<HTMLDivElement>(null),[spotlight,setSpotlight]=useState(new URLSearchParams(location.search).get('focus')||({homeowner:'home',dealer:'dealer',applicator:'app'} as Record<string,string>)[user.role]||(user.role==='presenter'?'story':'all'));
useEffect(()=>{if(chatScroll.current)chatScroll.current.scrollTop=chatScroll.current.scrollHeight},[s?.messages.length,s?.job?.id]);
useEffect(()=>{if(s?.scenario)setMode(s.scenario)},[s?.job?.id]);
useEffect(()=>{if(s?.job?.status==='COMPLETED')appScroll.current?.querySelector('.passport-card')?.scrollIntoView({block:'start',behavior:'smooth'})},[s?.job?.status]);
const presenter=user.role==='presenter';
async function load(){setCheckpointBusy(true);setCheckpointError('');try{const r=await fetch('/api/checkpoint?session='+id,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode,stage:checkpoint})}),d=await r.json();if(!r.ok)throw Error(d.error.message);await refresh(true);setTab('jobs')}catch(e){setCheckpointError(String(e))}finally{setCheckpointBusy(false)}}
if(!s)return <Notice tone="loading" title={error||'Opening the journey…'}/>;
const appAllowed=['presenter','applicator'].includes(user.role),homeAllowed=['presenter','homeowner'].includes(user.role),dealerAllowed=['presenter','dealer'].includes(user.role);
const disabledCommand=async()=>false,appCommand=appAllowed?command:disabledCommand,homeCommand=homeAllowed?command:disabledCommand;
const scenes={start:'Booked visit',quote:'Plan options',kit:'Materials ready',execution:'Work started',review:'Evidence review',reused:'Product exception',completed:'Completed job'};
return <section className="workflow pitch-workflow"><div className="pitch-controls"><label><span>Experience</span><select aria-label="Presenter spotlight" value={spotlight} onChange={e=>setSpotlight(e.target.value)}><option value="story">Present Ananya’s journey</option><option value="all">Explore connected interfaces</option><option value="app">Applicator app</option><option value="home">Homeowner · connected conversation</option><option value="live-home">Homeowner · current job</option><option value="dealer">Dealer experience</option></select></label>{spotlight!=='story'&&<label><span>Customer journey</span><select aria-label="Scenario" value={mode} onChange={e=>setMode(e.target.value)}><option value="terrace">Terrace · Ardex lead</option><option value="bathroom">Bathroom · own customer</option></select></label>}{presenter&&spotlight!=='home'&&spotlight!=='story'&&<><label><span>Jump to</span><select aria-label="Checkpoint" value={checkpoint} onChange={e=>setCheckpoint(e.target.value)}>{Object.entries(scenes).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><button className="primary" disabled={checkpointBusy||pending.length>0} onClick={load}>{checkpointBusy?'Opening…':'Show journey'}</button></>}</div>{(error||checkpointError)&&<Notice tone="blocked" title={error||checkpointError}/>} {!!pending.length&&<Notice tone="blocked" title={pending.length+' actions awaiting connection'}><button onClick={retryPending}>Reconnect & sync</button><button onClick={discardPending}>Discard pending actions</button></Notice>}
{spotlight==='story'?<GuidedPresentation s={s} command={command} busy={busy} refresh={refresh} user={user}/>:spotlight==='home'?<div className="connected-home-focus"><Phone kind="wa-device"><LiveConversation s={s} command={command} busy={busy} allowed={homeAllowed}/></Phone></div>:<><div className="pitch-journey-strip"><span>Enquiry & visit</span><i>→</i><span>Plan & approval</span><i>→</i><span>Materials & work</span><i>→</i><span>Verified handover</span></div><div className={'phone-stage pitch-phones spotlight-'+spotlight}>
<section className="phone-column"><div className="panel-title"><strong>Applicator app</strong><span className="pill">ARDEX PRO</span></div><Phone kind="app-device"><div className="work-phone-header"><img src="/brand/ardex-endura.png" alt="ARDEX ENDURA"/><b>PRO</b><span className="app-avatar">RK</span></div><div className="phone-scroll" ref={appScroll}>{!appAllowed&&<Notice title="Read-only app preview">Sign in as Applicator or Presenter to work on this job.</Notice>}{tab==='history'?<JobHistory/>:tab==='profile'?<ProfileView s={s} command={appCommand} busy={busy||!appAllowed}/>:tab==='earnings'?<><div className="step-label">YOUR BUSINESS</div><h2>Work that pays.</h2><div className="big-earning">{price(s.payments.reduce((n:number,p:any)=>n+p.amountPaise,0))}<small>Direct payment reported · not provider verified</small></div><div className="earnings-summary"><span>Released points<b>{s.points.reduce((n:number,p:any)=>n+(p.availableDelta??(p.status==='RELEASED'||p.status==='REVERSED'?p.amount:0)),0)}</b></span><span>Quality score<b>{s.profile.score}/100</b></span></div><Notice title="Quality and tier">{s.profile.tier} · Quality improves with completed, reviewed and rated jobs.</Notice><Notice title="Held points">{s.points.reduce((n:number,p:any)=>n+(p.heldDelta||0),0)} points await product, site and homeowner verification.</Notice><h3>Recent rewards</h3>{s.points.map((p:any)=><div className="ledger-row" key={p.id}><span>Job reward<small>{p.status.replaceAll("_"," ")}</small></span><b>{p.amount>0?"+":""}{p.amount}</b></div>)}</>:<>{!s.profile.loggedIn&&<ProfileView s={s} command={appCommand} busy={busy||!appAllowed}/>} {s.profile.loggedIn&&<><div className="app-greeting"><small>GOOD MORNING, RAVI</small><h2>Let’s get to work.</h2><span>{s.job?.status==='COMPLETED'?'Journey completed':s.job?'1 active journey':'Your next job is waiting'}</span></div>{(!s.job||!["IN_PROGRESS","REVIEW","HANDOVER","COMPLETED"].includes(s.job.status))&&<Intake s={s} command={appCommand} busy={busy||!appAllowed}/>}{s.job&&<>{['VISIT_BOOKED','DIAGNOSIS'].includes(s.job.status)&&<><details className="diagnosis-fold" open={!s.job.plan}><summary>Site diagnosis {s.job.plan&&'· edit and recalculate'}</summary><DiagnosisView key={s.job.id} s={s} command={appCommand} busy={busy||!appAllowed}/></details><PlanView key={s.job.diagnosis?.id||s.job.id} s={s} command={appCommand} busy={busy||!appAllowed}/></>}{!["IN_PROGRESS","REVIEW","HANDOVER","COMPLETED"].includes(s.job.status)&&<QuoteView s={s} command={appCommand} busy={busy||!appAllowed}/>}<KitView s={s} command={appCommand} busy={busy||!appAllowed}/><ProofView s={s} command={appCommand} busy={busy||!appAllowed}/><CancelControls s={s} command={appCommand} busy={busy||!appAllowed}/></>}</>}</>}</div><nav className="phone-nav">{['jobs','history','earnings','profile'].map((t,i)=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}><span>{['▦','◷','₹','◉'][i]}</span>{t}</button>)}</nav></Phone></section>
<section className="phone-column"><div className="panel-title"><strong>Homeowner</strong><span className="pill">WHATSAPP</span></div><Phone kind="wa-device"><div className="wa-header"><span>‹</span><div className="chat-avatar">S</div><div><b>Sakhaa · ARDEX</b><small>Business account</small></div><span>♧ ⋮</span></div><div className="wa-scroll" ref={chatScroll}><div className="wa-date">TODAY</div><div className="wa-encryption">Your visit, plan and work updates in one conversation.</div>{s.messages.length?s.messages.map((m:any)=><div className={'wa-bubble '+(['approval','rating'].includes(m.kind)?'outgoing':'')} key={m.id}><p>{m.text.replace(/\(demo\)/gi,'').replace(/\bdemonstration\b/gi,'sample').replace(/\bdemo\b/gi,'')}</p>{['introduction','booking','assignment','my-lead','quote','passport'].includes(m.kind)&&s.job&&<figure className="wa-site-photo"><img src={sitePhoto(s.job.areaType,m.kind==='passport'?'flood':'before')} alt="Site reference"/><figcaption>Generated reference</figcaption></figure>}{m.kind==='otp'&&<div className="wa-otp"><b>{m.code||'••••••'}</b><small>{m.purpose} · 30 minutes · homeowner confirmation</small></div>}{m.kind==='quote'&&<HomeownerQuote s={s} message={m} command={homeCommand} busy={busy||!homeAllowed}/>} {m.kind==='passport'&&<div className="wa-passport"><b>▤ Water Passport</b><small>{m.certificate.number.replace(/^DEMO-/, '')}</small><button className="wa-action" onClick={()=>exportDocument('passport',s,m.certificate)}>Download record</button><a className="wa-action" href={'/passport.html?token='+m.certificate.token} target="_blank">Verify record ↗</a>{!s.job.rating&&<div className="rating-buttons">{[1,2,3,4,5].map(n=><button key={n} disabled={!homeAllowed||busy} onClick={()=>command('RATE_JOB',{rating:n},'homeowner')}>{n} ★</button>)}</div>}</div>}<small className="wa-time">{new Date(m.at).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Kolkata'})}<span> ✓✓</span></small></div>):<div className="chat-empty"><h3>Your home,<br/>in safe hands.</h3><p>Quote, confirmations and proof appear here as your job moves forward.</p><button className="wa-action" onClick={()=>setSpotlight("home")}>Explore the complete WhatsApp journey</button></div>}</div><div className="wa-composer"><span>☺</span><div>Message</div><button disabled={!homeAllowed||!s.customer} onClick={()=>command('STOP_MESSAGES',{},'homeowner')}>Stop</button><span>●</span></div></Phone></section>
<section className="phone-column dealer-column"><div className="panel-title"><strong>Dealer</strong><span className="pill">SUPPLY & KIT</span></div><Phone kind="wa-device dealer-device"><DealerView s={s} command={command} busy={busy} allowed={dealerAllowed}/></Phone></section>
</div>{presenter&&s.job?.status==='IN_PROGRESS'&&spotlight!=='live-home'&&<div className="pitch-actions"><button disabled={busy} onClick={()=>command('SCAN_KIT',{},'presenter')}>Verify the material kit</button><button disabled={busy} onClick={()=>command('SCAN_PACK',{serial:'DEMO-USED',location:{...s.job.site,accuracy:12,mode:'sample'}})}>Try a reused pack</button><button disabled={busy} onClick={()=>command('NEXT_CURE',{},'presenter')}>Advance curing time</button><a href={adminUrl('/admin.html?session=')+id} target="_blank" rel="noreferrer">Review this job ↗</a></div>}</>}
</section>;
}

