import {DatabaseSync}from 'node:sqlite';import {randomUUID,randomBytes,scryptSync,timingSafeEqual,createHash}from 'node:crypto';import fs from 'node:fs';import path from 'node:path';import {initialState,applyCommand,verifyHistory,verifyState}from '../src/domain/authority.mjs';import {fixtures}from '../src/data/fixtures.mjs';import {handlers}from './handlers.mjs';import {nextStage}from '../src/domain/execution.mjs';
const root=path.resolve(import.meta.dirname,'..'),dir=path.join(root,'.runtime');fs.mkdirSync(dir,{recursive:true});export const db=new DatabaseSync(path.join(dir,'ardex-demo.sqlite'));db.exec('PRAGMA busy_timeout=5000; PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON; CREATE TABLE IF NOT EXISTS workspaces(id TEXT PRIMARY KEY,state TEXT NOT NULL,updated INTEGER NOT NULL); CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,name TEXT,role TEXT,salt TEXT,hash TEXT,disabled INTEGER DEFAULT 0); CREATE TABLE IF NOT EXISTS auth(token TEXT PRIMARY KEY,user_id TEXT REFERENCES users(id),expires INTEGER); CREATE TABLE IF NOT EXISTS registry(serial TEXT PRIMARY KEY,pack TEXT NOT NULL); CREATE TABLE IF NOT EXISTS settings(id TEXT PRIMARY KEY,value TEXT); CREATE TABLE IF NOT EXISTS audit(id TEXT PRIMARY KEY,user_id TEXT,action TEXT,details TEXT,at INTEGER);');
const fileCatalog=JSON.parse(fs.readFileSync(path.join(root,'config/catalog.json')));db.prepare('INSERT OR IGNORE INTO settings VALUES(?,?)').run('catalog',JSON.stringify(fileCatalog));db.prepare('INSERT OR IGNORE INTO settings VALUES(?,?)').run('routing',JSON.stringify({enabled:true,city:'BLR',radiusKm:15,offerMinutes:15}));
export const roles=['presenter','applicator','homeowner','dealer','admin','superadmin'];for(const role of roles){const salt=randomBytes(16).toString('hex');db.prepare('INSERT OR IGNORE INTO users(id,name,role,salt,hash) VALUES(?,?,?,?,?)').run(role,({presenter:'Pitch presenter',applicator:'Ravi Kumar',homeowner:'Demo homeowner',dealer:'Akshaya dealer',admin:'Operations administrator',superadmin:'System owner'})[role],role,salt,scryptSync('ArdexDemo!2026',salt,64).toString('hex'));}
export function audit(user,action,details){db.prepare('INSERT INTO audit VALUES(?,?,?,?,?)').run(randomUUID(),user,action,JSON.stringify(details),Date.now());}
export function catalog(){return JSON.parse(db.prepare('SELECT value FROM settings WHERE id=?').get('catalog').value);}
export function registry(){return Object.fromEntries(db.prepare('SELECT serial,pack FROM registry').all().map(r=>[r.serial,JSON.parse(r.pack)]));}
function savePacks(s,baseline=null){const stmt=db.prepare('INSERT INTO registry VALUES(?,?) ON CONFLICT(serial) DO UPDATE SET pack=excluded.pack');for(const r of Object.values(s.registry)){const value=JSON.stringify(r);if(!baseline||value!==JSON.stringify(baseline[r.serial]))stmt.run(r.serial,value);}}
for(const p of Object.values(initialState('registry',catalog()).registry))db.prepare('INSERT OR IGNORE INTO registry VALUES(?,?)').run(p.serial,JSON.stringify(p));
export function save(s){db.prepare('INSERT INTO workspaces VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET state=excluded.state,updated=excluded.updated').run(s.id,JSON.stringify({...s,registry:{}}),Date.now());}
export function load(id,hydrate=true){const row=db.prepare('SELECT state FROM workspaces WHERE id=?').get(id);let s;if(row)s=JSON.parse(row.state);else{const old=path.join(dir,id+'.json');s=fs.existsSync(old)?JSON.parse(fs.readFileSync(old)):initialState(id,catalog());s.catalog=catalog();save(s);}if(!verifyState(s))throw Error('Stored event chain is invalid');s.registry=hydrate?registry():{};return s;}
export function mutate(id,command,user){db.exec('BEGIN IMMEDIATE');try{const current=load(id);const result=applyCommand(current,command,handlers);if(!result.duplicate){if(command.type==='LOAD_SCENARIO'){result.state.registry=structuredClone(current.registry);for(const pack of Object.values(result.state.registry)){if(pack.consumedBy===current.job?.id)pack.consumedBy=null;}}savePacks(result.state,current.registry);save(result.state);audit(user,command.type,{session:id,job:result.state.job?.code,revision:result.state.revision});}db.exec('COMMIT');return result;}catch(e){db.exec('ROLLBACK');throw e;}}
export function login(id,password){const user=db.prepare('SELECT * FROM users WHERE id=?').get(id);if(!user||user.disabled||typeof password!=='string'||!timingSafeEqual(scryptSync(password,user.salt,64),Buffer.from(user.hash,'hex')))return null;const token=randomBytes(32).toString('hex');db.prepare('INSERT INTO auth VALUES(?,?,?)').run(createHash('sha256').update(token).digest('hex'),user.id,Date.now()+8*3600000);audit(user.id,'SIGN_IN',{role:user.role});return {token,user:{id:user.id,name:user.name,role:user.role}};}
export function authenticate(token){if(!token)return null;return db.prepare('SELECT u.id,u.name,u.role FROM auth a JOIN users u ON u.id=a.user_id WHERE a.token=? AND a.expires>? AND u.disabled=0').get(createHash('sha256').update(token).digest('hex'),Date.now());}
export function logout(token){if(token)db.prepare('DELETE FROM auth WHERE token=?').run(createHash('sha256').update(token).digest('hex'));}
export function run(s,type,payload={},actor='applicator'){return applyCommand(s,{id:randomUUID(),sessionId:s.id,expectedRevision:s.revision,type,payload,actor},handlers).state;}
export function seeded(id,mode,stage='start'){let s=initialState(id,catalog());s.registry=registry();s.profile.loggedIn=true;s.scenario=mode;if(mode==='terrace'){s=run(s,'OFFER_LEAD',{},'presenter');if(stage==='start')return s;s=run(s,'ACCEPT_LEAD');}else{s=run(s,'CREATE_MY_LEAD',{...fixtures.bathroom.customer,areaType:'BATHROOM',serviceConsent:true});if(stage==='start')return s;}s=run(s,'CHECK_IN',{location:{...s.job.site,accuracy:12,mode:'sample'}});const f=fixtures[mode];s=run(s,'SAVE_DIAGNOSIS',{answers:f.answers,measurement:f.measurement,photos:s.catalog.diagnosis_photos[f.areaType].map(view=>({view,mode:'sample'}))});s=run(s,'CALCULATE_PLAN');s=run(s,'SEND_QUOTE');if(stage==='quote')return s;const q=s.job.quotes.at(-1);s=run(s,'APPROVE_QUOTE',{quoteId:q.id,token:q.token,packageCode:q.selectedPackageCode},'homeowner');s=run(s,'TAG_DEALER',{dealerId:'dealer-001'});s=run(s,'READY_KIT',{},'dealer');if(stage==='kit')return s;s=run(s,'VERIFY_START',{purpose:'START',jobId:s.job.id,code:s.job.otps.START.code});s=run(s,'SCAN_KIT',{},'presenter');if(stage==='execution')return s;if(stage==='reused')return run(s,'SCAN_PACK',{serial:'DEMO-USED',location:{...s.job.site,accuracy:12,mode:'sample'}});while(nextStage(s)){const st=nextStage(s);s=run(s,'NEXT_CURE',{},'presenter');if(st.challenge_code)s=run(s,'REQUEST_CHALLENGE',{stageKey:st.key});s=run(s,'CAPTURE_STAGE',{stageKey:st.key,mode:'sample',location:{...s.job.site,accuracy:12,mode:'sample'},challengeCode:s.job.challenge?.code,weatherAcknowledged:true});if(stage!=='review')s=run(s,'ASSESS_CAPTURE',{captureId:s.job.captures.at(-1).id,status:'PASS',reason:'Seeded sample illustration inspected for demonstration',challengeConfirmed:true,floodResult:'PASS'},'admin');}if(stage==='review')return s;s=run(s,'EVALUATE_GATE',{},'admin');s=run(s,'REQUEST_CLOSE');s=run(s,'VERIFY_CLOSE',{purpose:'CLOSE',jobId:s.job.id,code:s.job.otps.CLOSE.code});s=run(s,'EVALUATE_GATE',{},'admin');s=run(s,'ISSUE_PASSPORT',{},'admin');if(stage==='completed'){s=run(s,'REPORT_PAYMENT',{amountPaise:s.job.approved.totalPaise});s=run(s,'RATE_JOB',{rating:5,comment:'Seeded demonstration rating'},'homeowner');}return s;}
export function checkpoint(id,mode,stage,user){if(!['start','quote','kit','execution','reused','review','completed'].includes(stage)||!['terrace','bathroom'].includes(mode))throw Error('Unknown checkpoint');db.exec('BEGIN IMMEDIATE');try{const old=db.prepare('SELECT state FROM workspaces WHERE id=?').get(id);if(old){const archive=JSON.parse(old.state);archive.id='archive-'+randomUUID();save(archive);}const s=seeded(id,mode,stage);s.loadedCheckpoint={stage,mode,at:Date.now(),explicitlySeeded:true};savePacks(s);save(s);audit(user,'LOAD_CHECKPOINT',{id,mode,stage,archived:!!old});db.exec('COMMIT');return s;}catch(e){db.exec('ROLLBACK');throw e;}}
if(!db.prepare('SELECT id FROM workspaces WHERE id LIKE ? LIMIT 1').get('seed-%')){for(const [i,stage]of ['quote','kit','execution','review','completed','reused'].entries())checkpoint('seed-'+(i+1),i%2?'bathroom':'terrace',stage,'system');}
export function summary(includeArchived=false){return db.prepare(includeArchived?'SELECT id,state,updated FROM workspaces ORDER BY updated DESC':"SELECT id,state,updated FROM workspaces WHERE id NOT LIKE 'archive-%' ORDER BY updated DESC").all().map(r=>{const s=JSON.parse(r.state);return {id:r.id,updated:r.updated,job:s.job,profile:s.profile,customer:s.customer,lead:s.lead,offer:s.offer,presentation:s.presentation,points:s.points,payments:s.payments,seeded:!!s.loadedCheckpoint};});}
export function publicPassport(token){for(const r of summary(true)){const c=r.job?.certificate;if(c?.token===token)return {certificate:c,system:c.system,area:c.area,stages:r.job.approved.stages.map(t=>({name:t.name,photos:r.job.captures.filter(c=>!c.superseded&&c.stageKey===t.key).length})),chainValid:verifyState(load(r.id,false)),demo:true};}return null;}




