import {handoverReadiness}from '../src/domain/execution.mjs';
import {serveStatic} from './static.mjs';
import http from 'node:http';import {DomainError}from '../src/domain/authority.mjs';import {db,load,mutate,login,authenticate,logout,summary,checkpoint,catalog,publicPassport,audit}from './database.mjs';
const grants={applicator:['CANCEL_JOB','REQUEST_LOGIN','VERIFY_LOGIN','SAVE_PROFILE','ACCEPT_LEAD','DECLINE_LEAD','CREATE_MY_LEAD','CHECK_IN','SAVE_DIAGNOSIS','CALCULATE_PLAN','SEND_QUOTE','REVISE_QUOTE','TAG_DEALER','REQUEST_OTP','VERIFY_START','SCAN_PACK','RECONCILE_SCAN','REQUEST_CHALLENGE','CAPTURE_STAGE','REQUEST_CLOSE','VERIFY_CLOSE','REPORT_PAYMENT','REQUEST_REPLACEMENT','CONFIRM_RECEIPT'],homeowner:['APPROVE_QUOTE','DECLINE_QUOTE','RATE_JOB','STOP_MESSAGES','ENQUIRY_REPLY','ACK_PAYMENT','CARE_CHOICE','REQUEST_SUPPORT','RESUME_MESSAGES'],dealer:['READY_KIT','SUPPLY_REPLACEMENT','RECORD_INVOICE','DEALER_SHORTAGE'],admin:['SET_CERTIFICATION','CLEAR_STRUCTURAL','RESOLVE_SCAN','ASSESS_CAPTURE','REDO_STAGE','EVALUATE_GATE','ISSUE_PASSPORT','VOID_PASSPORT','RESOLVE_SUPPORT','RECONCILE_INVOICE','RESOLVE_SHORTAGE','ADMIN_REOFFER']};
const allowedActor=(role,type)=>role==='presenter'?Object.entries(grants).find(([,types])=>types.includes(type))?.[0]||(['OFFER_LEAD','ADVANCE','SCAN_KIT','NEXT_CURE','NOTE','START_STORY','INJECT_WRONG_SKU'].includes(type)?'presenter':null):role==='superadmin'?(grants.admin.includes(type)?'admin':null):grants[role]?.includes(type)?role:null;
function fail(code,message,status=400){const e=new DomainError(code,message);e.status=status;throw e;}
function project(s,role){s=structuredClone(s);if(s.job?.approved)s.handoverReadiness=handoverReadiness(s);delete s.registry;delete s.receipts;if(s.offer?.status==='OFFERED'&&s.lead&&role!=='admin'&&role!=='superadmin'){delete s.lead.customer.phone;delete s.lead.customer.address;}if(!['presenter','admin','superadmin','homeowner'].includes(role)){for(const m of s.messages)delete m.code;for(const otp of Object.values(s.job?.otps||{}))if(otp)delete otp.code;}if(role==='homeowner'){s.profile={name:s.profile.name,tier:s.profile.tier,status:s.profile.status};s.events=[];s.points=[];s.payments=[];if(s.lead)delete s.lead.attribution;if(s.job)delete s.job.attribution;}return s;}
const attempts=new Map();function send(res,status,value){res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(JSON.stringify(value));}
async function body(req){let data='';for await(const c of req){data+=c;if(data.length>12*1024*1024)fail('TOO_LARGE','Payload too large',413);}return data?JSON.parse(data):{};}
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://127.0.0.1');if(!url.pathname.startsWith('/api/'))return serveStatic(req,res,url);if(url.pathname==='/api/health')return send(res,200,{ok:true,mode:'SQLite local demo',authentication:'server enforced roles'});if(url.pathname.startsWith('/api/public/')){const result=publicPassport(url.pathname.split('/').at(-1));return send(res,result?200:404,{ok:!!result,value:result});}
const host=req.headers.origin||req.headers.referer||req.headers['x-forwarded-host']||req.headers.host||'',cookieName=(host.includes('5175')||new URL(req.headers.referer||'/', 'http://localhost').pathname==='/admin.html')?'ardex_admin_auth':'ardex_app_auth';const token=req.headers.authorization?.replace(/^Bearer /,'')||req.headers.cookie?.split('; ').find(c=>c.startsWith(cookieName+'='))?.split('=')[1];
const trustedOrigins=[process.env.PUBLIC_ORIGIN,process.env.RAILWAY_PUBLIC_DOMAIN&&'https://'+process.env.RAILWAY_PUBLIC_DOMAIN].filter(Boolean);if(req.method!=='GET'&&req.headers.origin&&!trustedOrigins.includes(req.headers.origin)&&!(process.env.NODE_ENV!=='production'&&/^http:\/\/(127\.0\.0\.1|localhost):(5173|5175|4173)$/.test(req.headers.origin)))fail('ORIGIN','Untrusted demo origin',403);
if(url.pathname==='/api/login'&&req.method==='POST'){const p=await body(req),key=req.socket.remoteAddress,record=attempts.get(key)||{count:0,at:Date.now()};if(Date.now()-record.at>60000){record.count=0;record.at=Date.now();}record.count++;attempts.set(key,record);if(record.count>20)fail('LOGIN_LIMIT','Wait one minute before trying again',429);const result=login(p.id,p.password);if(!result)fail('LOGIN_FAILED','Incorrect or disabled demo account',401);res.setHeader('Set-Cookie',`${cookieName}=${result.token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=28800${process.env.NODE_ENV==='production'?'; Secure':''}`);return send(res,200,{ok:true,user:result.user});}
const user=authenticate(token);if(!user)fail('SIGN_IN','Sign in to the demo',401);if(url.pathname==='/api/me')return send(res,200,{ok:true,user});if(url.pathname==='/api/logout'){logout(token);res.setHeader('Set-Cookie',`${cookieName}=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0`);return send(res,200,{ok:true});}
if(url.pathname==='/api/stock'){if(!['presenter','dealer','admin','superadmin'].includes(user.role))fail('FORBIDDEN','Supply access required',403);const stockSession=url.searchParams.get('session');if(!stockSession||!/^[a-zA-Z0-9-]{1,80}$/.test(stockSession))fail('SESSION_ID','Valid session code required');const s=load(stockSession);if(user.role==='dealer'&&s.job?.kit?.dealerId!=='dealer-001')fail('NOT_ASSIGNED','Supply access belongs to the tagged dealer',403);return send(res,200,{ok:true,value:Object.values(s.registry).filter(r=>!r.consumedBy&&(!r.reservedFor||r.reservedFor===s.job?.id)&&r.sku===url.searchParams.get('sku')&&r.size===Number(url.searchParams.get('size'))).slice(0,20).map(r=>({serial:r.serial,sku:r.sku,size:r.size,unit:r.unit}))});}if(url.pathname==='/api/jobs'){const jobs=summary().filter(r=>r.job&&!r.id.startsWith('archive-')&&(user.role==='applicator'?r.job.applicatorId==='app-ravi':user.role==='dealer'?r.job.kit?.dealerId==='dealer-001':true)).map(r=>({id:r.id,code:r.job.code,status:r.job.status,areaType:r.job.areaType,mode:r.job.mode,customer:r.customer?.name,valuePaise:r.job.approved?.totalPaise||null,seeded:r.seeded}));return send(res,200,{ok:true,value:jobs});}if(url.pathname==='/api/admin'){if(!['admin','superadmin','presenter'].includes(user.role))fail('FORBIDDEN','Administration access required',403);return send(res,200,{ok:true,value:{workspaces:summary(),users:db.prepare('SELECT id,name,role,disabled FROM users').all(),catalog:catalog(),routing:JSON.parse(db.prepare('SELECT value FROM settings WHERE id=?').get('routing').value),pilot:JSON.parse(db.prepare('SELECT value FROM settings WHERE id=?').get('pilot')?.value||'{"acceptedVisitTarget":20,"recruitmentWeeksAfterReadiness":6,"approved":false}'),audit:db.prepare('SELECT * FROM audit ORDER BY at DESC LIMIT 100').all()}});}
if(url.pathname==='/api/config'&&req.method==='POST'){if(user.role!=='superadmin')fail('FORBIDDEN','Super Admin access required',403);const p=await body(req);if(p.kind==='user'){if(p.id==='superadmin')fail('OWNER_LOCK','The demo system owner cannot be disabled');if(!db.prepare('SELECT id FROM users WHERE id=?').get(p.id))fail('ACCOUNT_UNKNOWN','Account does not exist');if(typeof p.disabled!=='boolean')fail('CONFIG_VALUE','Choose a boolean account access state');db.prepare('UPDATE users SET disabled=? WHERE id=?').run(p.disabled?1:0,p.id);db.prepare('DELETE FROM auth WHERE user_id=?').run(p.id);}else if(p.kind==='routing'){if(!Number.isFinite(p.value.radiusKm)||p.value.radiusKm<1||p.value.radiusKm>15)fail('CONFIG_VALUE','Radius must be from 1 to 15 km');db.prepare('UPDATE settings SET value=? WHERE id=?').run(JSON.stringify(p.value),'routing');}else if(p.kind==='pilot'){if(!Number.isInteger(p.value?.acceptedVisitTarget)||p.value.acceptedVisitTarget<1||p.value.acceptedVisitTarget>100||!Number.isInteger(p.value.recruitmentWeeksAfterReadiness)||p.value.recruitmentWeeksAfterReadiness<1||p.value.recruitmentWeeksAfterReadiness>26)fail('CONFIG_VALUE','Use 1–100 accepted visits and 1–26 recruitment weeks');db.prepare('INSERT INTO settings VALUES(?,?) ON CONFLICT(id) DO UPDATE SET value=excluded.value').run('pilot',JSON.stringify({...p.value,approved:false}));}else if(p.kind==='catalog'){const c=catalog(),sku=c.skus.find(k=>k.code===p.sku),pack=sku?.packs.find(k=>k.size===Number(p.size));if(!pack||!Number.isInteger(p.pricePaise)||p.pricePaise<=0||p.pricePaise>100000000)fail('CONFIG_VALUE','Select a product pack and positive price');pack.price_paise=p.pricePaise;c._meta.version='demo-'+Date.now();db.prepare('UPDATE settings SET value=? WHERE id=?').run(JSON.stringify(c),'catalog');}else fail('CONFIG_KIND','Unknown configuration');audit(user.id,'CONFIG_'+p.kind,p);return send(res,200,{ok:true});}
const id=url.searchParams.get('session');if(!id||!/^[a-zA-Z0-9-]{1,80}$/.test(id))fail('SESSION_ID','Valid session code required');if(url.pathname==='/api/checkpoint'&&req.method==='POST'){if(user.role!=='presenter'&&user.role!=='superadmin')fail('FORBIDDEN','Presenter or Super Admin checkpoint access required',403);const p=await body(req);return send(res,200,{ok:true,value:project(checkpoint(id,p.mode,p.stage,user.id),user.role)});}
if(url.pathname==='/api/state'&&req.method==='GET')return send(res,200,{ok:true,value:project(load(id,false),user.role)});
if(url.pathname==='/api/command'&&req.method==='POST'){const command=await body(req),actor=allowedActor(user.role,command.type);if(!actor||actor!==command.actor)fail('FORBIDDEN','Your role cannot perform this action',403);const s=load(id);if(user.role==='dealer'&&s.job?.kit?.dealerId!=='dealer-001')fail('NOT_ASSIGNED','This supply request belongs to another dealer',403);if(user.role==='applicator'&&s.job&&s.job.applicatorId!=='app-ravi')fail('NOT_ASSIGNED','This job is assigned to another applicator',403);const result=mutate(id,command,user.id);return send(res,200,{ok:true,value:project(result.state,user.role),duplicate:result.duplicate});}fail('ROUTE_UNKNOWN','No implemented endpoint',404);
}catch(e){send(res,e.status||(e.code==='STALE_REVISION'?409:400),{ok:false,error:{code:e.code||'SERVICE_ERROR',message:e.message,retry:!!e.retry}});}}).listen(Number(process.env.PORT??5174),process.env.HOST||(process.env.NODE_ENV==='production'?'0.0.0.0':'127.0.0.1'),()=>console.log('ARDEX PRO listening on port '+server.address().port));
process.on('SIGTERM',()=>server.close(()=>{db.close();process.exit(0);}));





