import {presentState}from '../ui/presentation';
import {useCallback,useEffect,useRef,useState}from 'react';
export function useWorkspace(id:string){
 const [state,setState]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[pending,setPending]=useState<any[]>(()=>{try{return JSON.parse(localStorage.getItem('ardex-outbox:'+id)||'[]')}catch{return []}});const revision=useRef(-1),activeId=useRef(id);activeId.current=id;
 const receive=useCallback((s:any)=>{if(s.id===id&&activeId.current===id&&s.revision>=revision.current){revision.current=s.revision;setState(presentState(s))}},[id]);
 const refresh=useCallback(async(reset=false)=>{const r=await fetch('/api/state?session='+id),d=await r.json();if(!r.ok)throw Error(d.error?.message||'Service unavailable');if(reset)revision.current=-1;receive(d.value);return d.value},[id,receive]);
 useEffect(()=>{revision.current=-1;setState(null);try{setPending(JSON.parse(localStorage.getItem('ardex-outbox:'+id)||'[]'))}catch{setPending([])};let active=true;const poll=()=>refresh().catch(()=>{if(active)setError('Local service unavailable or sign-in expired. Pending actions are retained.')});poll();const timer=setInterval(poll,1500);return()=>{active=false;clearInterval(timer)}},[refresh]);
 const persist=(items:any[])=>{localStorage.setItem('ardex-outbox:'+id,JSON.stringify(items));setPending(items)};
 const command=useCallback(async(type:string,payload:any={},actor='applicator',commandId=crypto.randomUUID())=>{if(busy)return false;setBusy(true);const envelope={id:commandId,sessionId:id,expectedRevision:revision.current,expectedJobId:state?.job?.id||null,type,payload,actor};try{let r=await fetch('/api/command?session='+id,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(envelope)}),d=await r.json();if(r.status===409&&d.error.code==='STALE_REVISION'){const current=await refresh();if(state?.job?.id&&current.job?.id!==state.job.id)throw Error('Job changed; review the new workspace before retrying.');envelope.expectedRevision=current.revision;r=await fetch('/api/command?session='+id,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(envelope)});d=await r.json();}if(!r.ok)throw Error(d.error?.message||'Action rejected');receive(d.value);setError('');return true;}catch(e){if(e instanceof TypeError&&['SCAN_PACK','CAPTURE_STAGE'].includes(type)){try{persist([...pending,{...envelope,queuedAt:Date.now(),baselineJobId:state?.job?.id,ownerRole:actor}]);setError('Saved as pending evidence. It has not passed authoritative checks.')}catch{setError('Device storage is full; evidence was not queued.')}}else setError(String(e));return false;}finally{setBusy(false)}},[busy,id,pending,state,receive,refresh]);
 async function retryPending(){setBusy(true);try{await refresh();const queue=[...pending];for(let i=0;i<pending.length;i++){const item=pending[i],r=await fetch('/api/state?session='+id),d=await r.json();if(!r.ok)throw Error(d.error.message);if(d.value.job?.id!==item.baselineJobId)throw Error('Pending evidence belongs to an earlier job; review or discard it.');const response=await fetch('/api/command?session='+id,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...item,expectedRevision:i===0?item.expectedRevision:d.value.revision})}),result=await response.json();if(!response.ok)throw Error(result.error.message+' Pending evidence retained for review.');receive(result.value);queue.shift();persist(queue);}setError('');}catch(e){setError(String(e));}finally{setBusy(false)}}
 return {state,error,busy,command,refresh,pending,retryPending,discardPending:()=>persist([])};
}


